project:
  type: website
  output-dir: docs
  resources:
    - "*.css"
    - "*.pdf"


website:
  title: "The American Psychology-Law Society"
  favicon: "assets/favicon_io/favicon.ico"
  search: true
  
  navbar:
    title: false
    logo: images/logo-light.png
    right:
      - text: About
        menu:
          - text: About
            href: about/about.qmd
          - text: Leadership
            href: about/leadership.qmd
          - text: Committees
            href: about/committees.qmd
          - text: Statements
            href: about/statements.qmd
          - text: AP-LS Bylaws
            href: about/bylaws.qmd
          - text: Contact us
            href: about/contact.qmd
      - text: Publications
        menu:
          - text: Publications
            href: publications/index.qmd
          - text: Law & Human Behavior
            href: https://www.apa.org/pubs/journals/lhb/
      - href: awards/index.qmd
        text: Awards
      - href: conferences/index.qmd
        text: Conferences
      - href: resources/index.qmd
        text: Resources
      - href: membership/membership.qmd
        text: Membership
        
  sidebar: 
    - id: about us
      title: "About AP-LS"
      style: "docked"
      search: true
      contents:
        - section: "Our Mission"
          contents:
          - about/about.qmd
          - about/statements.qmd
          - about/bylaws.qmd
        - section: "Our History"
          contents:
          - about/history.qmd
          - about/presidents/presidents.qmd
        - section: "Who we are"
          contents: 
            - about/leadership.qmd
            - about/committees.qmd
            - about/contact.qmd
        
    - id: guidelines
      title: "Forensic Guidelines"
      search: true
      contents: 
        - section: "Sections"
          contents: 
            - resources/guidelines/index.qmd
            - resources/guidelines/Introduction.qmd
            - resources/guidelines/Responsibilities.qmd
            - resources/guidelines/Competence.qmd
            - resources/guidelines/Diligence.qmd
            - resources/guidelines/Relationship.qmd
            - resources/guidelines/Fees.qmd
            - resources/guidelines/Consent.qmd
            - resources/guidelines/Conflicts.qmd
            - resources/guidelines/Privacy.qmd
            - resources/guidelines/Methods.qmd
            - resources/guidelines/Assessment.qmd
            - resources/guidelines/Communications.qmd
            - resources/guidelines/References.qmd
        
       
  page-footer:
    left: |
      <b>© 2022 American Psychology-Law Society</b>  <br>
      made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)
    right:
      - icon: twitter
        href: https://twitter.com/apls41
      - icon: github
        href: https://github.com/emmarshall 

format:
  html:
    theme: 
      light: [flatly, assets/light-theme.scss]
      dark: [darkly]
    css: assets/styles.css


execute: 
  freeze: true



