project:
  type: website
  output-dir: docs
  resources:
    - "*.css"
    - "*.pdf"

website:
  site-url: https://ap-ls.netlify.app/
  repo-url: https://github.com/emmarshall/emmarshall.github.io
  repo-actions: [edit, issue]

website:
  title: "The American Psychology-Law Society"
  favicon: "assets/favicon_io/favicon.ico"
  search: true
  
  navbar:
    title: false
    logo: images/logo-light.png
    right:
      - text: About
        menu:
          - text: About
            href: about/about.qmd
          - text: Leadership
            href: about/leadership.qmd
          - text: Committees
            href: about/committees.qmd
          - text: Statements
            href: about/statements.qmd
          - text: AP-LS Bylaws
            href: about/bylaws.qmd
          - text: Contact us
            href: about/contact.qmd
      - text: Publications
        menu:
          - text: Publications
            href: publications/index.qmd
          - text: Law & Human Behavior
            href: https://www.apa.org/pubs/journals/lhb/
      - href: awards/index.qmd
        text: Awards
      - text: Conferences
        menu:
          - text: 2023 AP-LS Conference
            href: conferences/index.qmd
          - text: Program & Schedule
            href: conferences/schedule.qmd
      - href: resources/index.qmd
        text: Resources
      - href: membership/membership.qmd
        text: Membership
        
  sidebar: 
    - id: about us
      title: "About AP-LS"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "Our Mission"
          href: about/about.qmd
          contents: 
            - text: "Policy Statements"
              href: about/statements.qmd
            - about/bylaws.qmd
        - section: "Our History"
          contents:
            - about/history.qmd
            - text: "Presidential archive"
              href: about/presidents/presidents.qmd
        - section: "Who we are"
          contents: 
            - about/leadership.qmd
            - about/committees.qmd
            - about/contact.qmd
        
    - id: guidelines
      title: "Forensic Guidelines"
      collapse-level: 1
      contents: 
        - text: "Basics"
          href: resources/guidelines/index.qmd
        - section: "Guidelines"
          contents: 
            - resources/guidelines/Introduction.qmd
            - resources/guidelines/Responsibilities.qmd
            - resources/guidelines/Competence.qmd
            - resources/guidelines/Diligence.qmd
            - resources/guidelines/Relationship.qmd
            - resources/guidelines/Fees.qmd
            - resources/guidelines/Consent.qmd
            - resources/guidelines/Conflicts.qmd
            - resources/guidelines/Privacy.qmd
            - resources/guidelines/Methods.qmd
            - resources/guidelines/Assessment.qmd
            - resources/guidelines/Communications.qmd
            - resources/guidelines/References.qmd
        
       
  page-footer:
    left: |
      <b>© 2023 American Psychology-Law Society</b>  <br>
      made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)
    right:
      - icon: twitter
        href: https://twitter.com/apls41
      - icon: facebook
        href: https://www.facebook.com/APLS41 
      - icon: instagram
        href: https://www.instagram.com/apls41/

format:
  html:
    theme: 
      light: [flatly, assets/light-theme.scss]
    css: assets/styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

freeze: true


