project:
  type: website
  output-dir: docs
  resources:
    - "*.css"
    - "*.pdf"
    - "*.Rhtml"

execute:
    freeze: auto
    
website:
  title: "The American Psychology-Law Society"
  favicon: "assets/favicon_io/favicon.ico"
  search: true
  
  navbar:
    title: false
    logo: images/logo-light.png
    right:
      - text: About
        menu:
          - text: About
            href: about/index.qmd
          - text: Leadership
            href: about/leadership.qmd
          - text: Committees
            href: about/committees.qmd
          - text: Statements
            href: about/statements.qmd
          - text: AP-LS Bylaws
            href: about/bylaws.qmd
          - text: Contact us
            href: about/contact.qmd
      - text: Publications
        menu:
          - text: AP-LS Newsletter
            href: newsletter/index.qmd
          - text: Publications
            href: publications/index.qmd
          - text: Law & Human Behavior
            href: https://www.apa.org/pubs/journals/lhb/
      - href: awards/index.qmd
        text: Awards
      - text: Conferences
        menu:
          - text: 2024 AP-LS Conference
            href: conferences/index.qmd
          - text: 2024 Program & Schedule
          - href: conferences/schedule.qmd
          - text: 2024 Preconference Workshops
            href: conferences/preconference/index.qmd
          - text: Past Conferences
            href: conferences/archive/index.qmd
      - href: resources/index.qmd
        text: Resources
      - href: membership/index.qmd
        text: Membership
        
  sidebar: 
    - id: about us
      title: "About AP-LS"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - section: "Our Mission"
          href: about/index.qmd
          contents: 
            - text: "Policy Statements"
              href: about/statements.qmd
            - about/bylaws.qmd
        - section: "Our History"
          contents:
            - about/history.qmd
            - text: "Presidential archive"
              href: about/presidents/presidents.qmd
        - section: "Who we are"
          contents: 
            - about/leadership.qmd
            - about/committees.qmd
            - about/contact.qmd
        
    - id: guidelines
      title: "Forensic Guidelines"
      collapse-level: 1
      contents: 
        - text: "Basics"
          href: resources/guidelines/index.qmd
        - section: "Guidelines"
          contents: 
            - resources/guidelines/Introduction.qmd
            - resources/guidelines/Responsibilities.qmd
            - resources/guidelines/Competence.qmd
            - resources/guidelines/Diligence.qmd
            - resources/guidelines/Relationship.qmd
            - resources/guidelines/Fees.qmd
            - resources/guidelines/Consent.qmd
            - resources/guidelines/Conflicts.qmd
            - resources/guidelines/Privacy.qmd
            - resources/guidelines/Methods.qmd
            - resources/guidelines/Assessment.qmd
            - resources/guidelines/Communications.qmd
            - resources/guidelines/References.qmd
    
       
  page-footer:
    left: |
      Copyright &copy; 2024 [American Psychology-Law Society](https://apls.memberclicks.net/)
    center: |
       [Report an issue](https://docs.google.com/forms/d/e/1FAIpQLSfOL2JsE-YbvqH09-S6zcukZ6qiOycK98DjXa08MDygMTWBYA/viewform?usp=sf_link)
    right:
      - icon: twitter
        aria-label: Link to Twitter
        href: https://twitter.com/apls41
      - icon: facebook
        aria-label: Link to Facebook
        href: https://www.facebook.com/APLS41 
      - icon: instagram
        aria-label: Link to Instagram
        href: https://www.instagram.com/apls41/
      - icon: youtube
        aria-label: youtube
        href: https://www.youtube.com/channel/UCHCZlqNOXNDDUPnMzBqTmQA
      - icon: envelope
        aria-label: Link to email
        href: mailto:office@ap-ls.org

format:
  html:
    theme: 
      light: [assets/light-theme.scss]
      dark: [assets/dark-theme.scss]
    css: assets/styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px



