---
title: Overview of ap-ls.org
author: Emma Marshall
---

## Website Basics

This ap-ls.org website is built in [RStudio](https://www.rstudio.com/) using [Quarto](https://quarto.org). The content for the site is stored on the AP-LS Google Drive and on [GitHub](https://github.com). The site is published using [Netlify](https://www.netlify.com/). When the site is updated in the Github respository, the new published content will appear in the `_site` directory.


## Site file structure

The main content for the site is stored in the following files and directories:

- `_quarto.yml` controls site-wide parameters and is where navbar and footer contents are specified
- `_variables.yml` controls site-wide variables, such as the email used in our contact page
- `index.qmd` is the site's home page
- `about`, `contact`, `documents`, `events`, and `news` contain those respective pages for the site
  - `documents`, `events`, and `news` are listing pages
      - The `index.qmd` file in each directory controls parameters for the post listings
  - `contact` has a listing section for displaying member profiles
      - The profiles are created in the `members.yml` file in the `contact` directory
      - Profile pictures are stored in the `avatars` directory
- `404.qmd` is the 404 page for the site
- `styles.css` and `theme.scss` in the `assets` directory are used for additional CSS and SASS styling for the site's appearance, such as fonts and colors

Other files:

- `_templates` contains templates you can use for creating new posts for the sites various listing pages.     - Please see the `README.md` file inside `_templates` or the [New Post Workflow](/documents/posts/new-post-workflow) document for more information
- `_common` includes files that are common to several pages across the site
    - Please see the `README.md` file inside `_common` for more information
- `_site` contains the files for the rendered site
    - Do not modify anything in this directory directly, it's pointless
        - Whenever you render the site it will be overwritten. 

## Creating and editing content

Add section details. 

## How to Quarto

Please see the [getting started](https://quarto.org/docs/get-started/) page for installation information, and the Quarto [guide](https://quarto.org/docs/guide/) and [reference](https://quarto.org/docs/reference/) for information on how the site was built and how you can modify it.