
::: {.simple-info-center}

## Call for Proposals{#proposals}

[Annual Conference of the American Psychology-Law Society (AP-LS) | March 13-15, 2025 \| San Juan, Puerto Rico \| Sheraton Puerto Rico Resort & Casino]{.event-time}

:::

[Call for Proposals]{.plenary}

::: session-description
We invite proposal submissions for the 2025 Annual Conference of AP-LS. We strongly encourage empirically based proposals, proposals that involve new and emerging topics within psychology and law, and proposals that incorporate historically marginalized or underrepresented populations.

This year, we are particularly interested in proposals that highlight collaboration, broadly defined. This could include collaboration across multiple research labs, collaboration across professional fields, collaborations in expertise and experience, or collaborations across organizations. We strongly encourage “adversarial” collaborations, or those among scholars who take different approaches or views of an issue.

Proposals will be evaluated through a blind review process focused on intellectual merit, innovation, novelty, and integration of multiple aspects of the field.
:::

::: callout-note
## Submission Details

<center>
All proposals must be submitted on the conference website by <br> [Monday, September 30, 2024, 11:59 pm PST]{.session-time}

Visit the conference website to register, submit your proposals, AND sign up as a reviewer!

[{{< fa user-plus aria-hidden="true" >}} Register here](https://ap-ls2025.exordo.com/login){.btn .btn-outline-primary role="button"}

</center>
:::

::: vspace
:::

[Symposia]{.plenary}

::: session-description
**Symposia (up to 80 min):** A single topic coordinated group of presentations with a minimum of 3 and maximum of 5 presentations and an independent discussant. The participation of each presenter should be secured before submission. Submissions are limited to a 200-word abstract for the symposium session, 3-4 overarching learning objectives, and a 100-word abstract plus 1000-word summary for each paper. You must also submit CVs for each presenter. All symposia material must be proposed in a single submission.
:::

[Papers]{.plenary}

::: session-description
**Papers:** Presentation of a paper describing an individual research topic OR piece of legal scholarship. Submissions are limited to a 100-word abstract, 1000-word summary, and 1-2 learning objectives.
:::

[Data-blitz]{.plenary}

::: session-description
**Data-blitz:** A 5-minute presentation (limit 3 slides) covering a bite-sized piece of psycho-legal research. Submissions are limited to a 100-word abstract, 1000-word summary, and 1-2 learning objectives. The sessions will offer a fast-paced overview of the exciting emerging research. Data-blitz sessions will not be organized by topic (great for research and legal scholarship that does not traditionally fit with other AP-LS sessions!).
:::

[Posters]{.plenary}

::: session-description
**Posters:** will be presented at one of two poster sessions held Friday and Saturday evenings. Posters are presented in written format on display boards. Submissions are limited to a 100-word abstract and 1000-word summary. We encourage poster presenters to use a [Better Poster format](https://convention.apa.org/blog/rethinking-the-science-poster).

[{{< fa star aria-hidden="true" >}} NEW THIS YEAR!]{.highlight}

[Projects in Progress]{.plenary}

::: session-description
Authors can submit a “project in progress” to present a project in the conceptualization, pilot testing, and/or preliminary implementation phase. The purpose of these sessions is to present an early project idea and receive feedback from conference colleagues regarding roadblocks, considerations, and areas for potential collaboration. Submissions are limited to a 100-word abstract, 1000-word summary, and 1-2 learning objectives. Projects in progress will be limited to 2-3 similarly themed projects per session to allow for conversation and collaboration.
:::
:::

::: callout-note
-   Authors will indicate when submitting whether they would like their proposal to be considered as a 1) paper, 2) data-blitz, 3) poster, or 4) any combination of these.

-   There is a limit of **TWO** first-author symposia/paper/data-blitz submissions per person and ONE Project in Progress. There are no limits for the number of submissions for posters or appearances as a discussant or session chair.
:::

[Reviewers]{.plenary}

::: session-description
**Reviewers:** Reviewers are invited for all content areas including both professional and graduate student reviewers. Proposals will be distributed for review at the end of October. Please sign up to be a reviewer using the submission portal above. We will only be able to use reviewers who register via this online system.
:::


>If you have any questions or comments about the conference, please contact the conference co-chairs at [conference@ap-ls.org](mailto:conference@ap-ls.org)
Looking forward to seeing everyone in March! <br>
<br>*2025 AP-LS Conference Co-Chairs <br> Jenni Cox & Lori Hoetger Fendrick*


## {{< fa circle-user aria-hidden="true" >}} Conference Organizers

[Conference Contacts]{.plenary}

***Co-chairs:***<br> Jenni Cox & <br> Lori Hoetger Fendrick <br> {{< fa envelope title="Email" aria-hidden="true" >}} conference\@apl-ls.org
:::

<figure class="text-end">

<blockquote class="blockquote">

<p class="mb-0">

If you have any questions or comments about the conference, please contact the conference co-chairs at [conference@ap-ls.org](mailto:conference@ap-ls.org)

Looking forward to seeing everyone in March!

<figcaption class="blockquote-footer">

2025 AP-LS Conference Co-Chairs <cite title="Jenni Cox & Lori Hoetger Fendrick">Jenni Cox & Lori Hoetger Fendrick</cite>

</figcaption>

</figure>

