---
title: Campus Representative Program
draft: true
---

Thank you for your interest in the AP-LS Student Committee Campus Representative Program. The Executive Cabinet of the Student Committee is very excited to offer this unique opportunity to our student members. The information below is designed to provide you with detailed information about the Campus Representative Program, including the goals of the program, campus representative responsibilities, and the benefits of serving as a campus representative.

[Current representatives](https://docs.google.com/spreadsheets/d/1zecpafvxt8XaHmJvhIFAB7_a7G3EDRPPuFNf2h3OiG8/edit#gid=228742081)

### What Is the Campus Representative Program?

The Campus Representative Program is a program designed to facilitate communication among the Student Committee Executive Cabinet, professional AP-LS members, and AP-LS student affiliates. The primary goal of the program is the creation of a network of liaisons at as many colleges and universities as possible, with AP-LS student members serving as official representatives of the Student Committee and AP-LS at their local campuses. In addition, campus representatives help disseminate relevant information to their local student bodies, including information about opportunities, activities, and programs organized by the Student Committee and AP-LS.

The Student Committee Executive Cabinet recognizes the critical role our campus representatives play in the success of AP-LS's student-focused initiatives. Participating in the Campus Representative Program will afford students valuable leadership and professional development experience, and at the same time, help strengthen AP-LS through enhanced student recruitment, information dissemination, and membership solidarity. We encourage you to apply for a one-year term of service as a campus representative.

### Am I eligible to become a campus representative?

-   You must be an AP-LS student member (The annual student membership fee is \$15).

-   You must be enrolled at least part-time in an undergraduate or graduate psychology program, law school, or other relevant training program.

-   You must be the only campus representative for your respective program. (If your school has multiple relevant programs, e.g., a psychology department, a sociology/criminology department, a law school, email us about the possibility of serving alongside other students at your school who are based in different departments or programs.)

### How does joining the Campus Representative Program benefit me?

-   It's an easy way to increase your involvement in AP-LS.

-   Similarly, you'll increase your knowledge of the workings of AP-LS, as well as the many student-focused activities and opportunities that the association offers.

-   Your service as a campus representative is distinguishing, adding a valuable line on your CV.

-   Participating in the Campus Representative Program gives you an excellent opportunity to network and work alongside like-minded students and professionals located in North America and abroad---many of whom will be future colleagues and potential employers.

-   You'll obtain valuable leadership experience that will surely benefit you in your career. You'll have the opportunity to be of service to your local student colleagues, and perhaps most importantly, to introduce neophyte students to the fascinating field of psychology and law.

### What are my responsibilities as a campus representative?

You are required to regularly (i.e., at least monthly) use at least two effective forms of communication to distribute notices received in the monthly e-newsletter and through separate flier mailings and other initiatives. Communication outlet ideas include:

-   Send emails to entire department (i.e., an all\@psych list).

-   Send emails to graduate and undergraduate student-only lists.

-   Send emails to faculty-only lists, with the request that faculty members share the information with their advisers, labs, or entire classes if appropriate.

-   Regularly post fliers on departmental bulletin boards (Many departments have several, and printing the fliers in color or on brightly colored paper is especially effective).

-   Place fliers in department mailboxes.Make announcements during various psychology-related meetings (e.g., Psi Chi, psychology club meetings, small departmental gatherings, faculty meetings, and lab meetings).

-   Depending on the policies of your institution, some classes permit outside announcements to be made at the beginning of class, or to have an overhead left on the projector while students file into or out of class.

-   Forward information to the departmental student services officer (aka, graduate/undergraduate advisor) and ask if they have any other effective strategies for disseminating the information.

    -   You are also required to regularly complete brief campus representative reports for the Student Committee on a semesterly basis.

    -   Finally, you are also required to identify goals that you plan to work on during your term. Most goals that campus representatives set have to do with the conference (e.g., encouraging submissions, facilitating applications for travel awards, helping pair up students for room sharing) or increasing awareness (e.g., hosting an informational session about AP-LS, encouraging engagement in committees).

Remember that anything you do in the capacity of an AP-LS Student Committee campus representative should always reflect well on the Student Committee and AP-LS.

## What other information do I need to know about the program?

-   The campus representative term is for up to one school year in length. Specifically, the campus representative term length begins and ends the first of August (e.g., August 1 to July 31) regardless of when a campus representative signs up. So if a campus representative signs up in July 2021, he or she will be the campus representative from August 1, 2021 to July 31, 2022. But if they sign up on October 7, 2020, they will be campus representative from October 7, 2020 to July 31, 2021.

-   Our goal is for each program to have a Campus Representative Program faculty sponsor who can assist in sustaining the local campus representative position over time. If your program does not have a faculty sponsor, we ask that you try to establish one. Many programs already do have Campus Representative Program faculty sponsors. A campus representative will work with the faculty sponsor to ensure continuity of service during campus representative-to-campus representative transitions each year.

-   To that end, we request that you find a replacement before concluding your term as campus representative. If your program has a Campus Representative Program faculty sponsor, he or she can help. If you cannot find a replacement, you should make arrangements for a temporary contact within your psychology department to post notices/fliers. When a replacement is located, you should make your methods for distribution of information available to them and inform the Student Committee of your replacement. Notably, some campuses have decided to use election processes to facilitate this process while other campuses use volunteers. So, you should identify what is expected on your campus before handing off the position.

-   You are required to supply the Student Committee with current contact information that can be posted on the AP-LS website, including your name, campus, and email address.

-   You are required to place your contact information at the bottom of any fliers that you distribute. No other changes or deletions should be made to the fliers.You will be asked to assist in coordinating students from your campus who would like to share costs associated with attending the annual AP-LS conference. This could be as simple as introducing everyone who is planning on attending to each other via email so that they can arrange travel and accommodation together.

How do I apply for the position of campus representative? To apply to become a campus representative, [please fill out the online form](https://docs.google.com/forms/d/e/1FAIpQLSd-hb9lnqs4BmtZI8e3JDI9FCAk3tKzg0TQoXIK1Vpm_HMNlg/viewform) Before applying, be sure to confirm first whether your school/program currently has a campus representative. See the current campus representatives. Feel free to email the Student Committee's [campus representative coordinator](aplscampusrep@gmail.com) if you have questions about applying or need additional information.

Thank you again for your interest in the AP-LS Student Committee Campus Representative Program. The Student Committee Executive Cabinet looks forward to working with you in helping to better reach and serve students interested in studying the intersections of psychology and law.
