---
title: AP-LS Student Committee
title-block-banner: "../../images/banners/default-banner.png"
---


The American Psychology-Law Society (AP-LS) Student Committee works to advance the interests of student affiliates within the division, including by enhancing communication among student affiliates and between student affiliates and other members in the society, enhancing the participation of student affiliates in society affairs, and generally advancing the professional development of student affiliates.

Although many of our resources are reflected on this website, check out our dynamic [unofficial website](https://www.apls-students.org/) for up-to-date information on funding opportunities, job postings, webinars, and other student-focused programming. We are active on social media---please like our Facebook page or connect with us on Twitter @APLSsc for access to the most recent information from the Student Committee. Email us with direct questions at {{< fa envelope title="Email" >}} {{< var email.students >}}.

Students interested in getting involved with the Student Committee should first become student affiliates of AP-LS. In addition, they should consider joining Div. 41's parent association, the American Psychological Association (APA), as a student affiliate. Graduate students who join APA are also automatically members of the American Psychological Association of Graduate Students (APAGS). The yearly dues to each are offset by the numerous benefits afforded exclusively to student members.

Undergraduate, graduate, or professional students (who are AP-LS student affiliates) may apply to serve as AP-LS Student Committee Campus Representatives. In addition, and as per our bylaws, elections for Student Committee officer positions are held each year in the summer.


::: column-screen
::: {.simple-info-blue .alt-background-blue}
::: content-block-blue
##### Want to learn more about the Student Campus Representative program? 

[Learn More {{< fa arrow-right >}}](campus_reps.qmd){.btn-action .btn .btn-secondary .btn-lg role="button"}
:::
:::
:::

::: vspace
:::

## Executive Committee

The Student Executive Committee consists of the following officers:

-   Chair
-   Chair-Elect
-   Past Chair
-   Secretary
-   Communications Officer
-   Campus Representative Coordinator
-   Members at Large/Liaisons Clinical Liaison
    -   Experimental Liaison
    -   Law Liaison
    -   Diversity Liaison

## Elections 

Elections for the Executive Committee are held annually. Any current student member of AP-LS may self-nominate to run for election. The call for self-nominations takes place during late June. Elections are held online mid-July. All student affiliates of AP-LS are encouraged to vote. The winners of the election are announced in late July, and the official transition of officers takes place in early August.

Keep an eye on our [Facebook](https://www.facebook.com/apls.sc) and [Twitter](https://twitter.com/APLSsc) pages for updates about the self-nomination process and the annual election.

::: vspace
:::

::: column-screen
::: {.simple-info-blue .alt-background-blue}
::: content-block-blue
##### Want to see who is on the AP-LS Student Committee? Check out their website! 

[Learn More {{< fa arrow-right >}}](http://www.apls-students.org/){.btn-action .btn .btn-secondary .btn-lg role="button"}
:::
:::
:::

::: vspace
:::

## Student Resources  

#### Graduate Programs in Psychology and Law 

If you are interested in learning more about graduate programs, please review the links to the degree programs provided on this web site, and also review the [Guide to Graduate Programs in Legal and Forensic Psychology](http://ap-ls.wildapricot.org/resources/Documents/GuidetoGraduateProgramsinForensicPsych.pdf "Guide to Graduate Programs in Legal and Forensic Psychology"), developed by members of the AP-LS Teaching, Training, and Careers Committee (TTC). We hope this new format will allow students interested in psychology and law programs to more easily access and compare graduate programs. This guide lists current graduate programs in forensic and legal psychology. Programs are listed alphabetically by degree type: doctoral programs (PhD and PsyD), joint programs (PhD/JD, PsyD/JD, JD/MA, PhD/MLS), and masters-level programs. Each program is described using the same categories (program facts, admission criteria, opportunities for research or practica and funding availability) to help prospective students make informed choices about graduate training and education in psychology and law.

### Funding resources 

Graduate students seeking funding for their research may apply for the AP-LS Grants-in-Aid (1,000 maximum). Undergraduate students seeking funding can apply for the AP-LS Grants-in-Aid for Undergraduate Students starting January 2021.Students from underrepresented groups or students conducting research on diversity related issues are eligible to apply for the Minority Affairs Committee's Diversity in Psychology and Law Research Awards (\$1,000) and Diversity Travel Awards (\$500).

Each year, the Student Committee coordinates AP-LS conference presentation awards at the AP-LS annual conference. Students submit their presentations (be it a symposium paper, an individual paper, or a poster) for consideration and they are judged anonymously at the conference. The Student Committee disseminates information about how to apply for its awards each year.

Check out our [unofficial website](https://www.apls-students.org/) for more great funding resources, including an up-to-date list of awards for students.

### Training resources 

The Student Committee clinical liaison develops a [predoctoral internship resource guide](https://drive.google.com/file/d/0BwHHGLhi_4i-dnR4Q3FheHpaNW8/edit?resourcekey=0-K8LDLfwzZegBjpKQxGup-A), [clinical postdoctoral positions](https://www.apls-students.org/clinical.html) and hosts a listing of predoctoral internships and [research postdoctoral positions](https://www.apls-students.org/research.html) that have at least some element of training in forensic psychology.

Students and professionals interested in legal training may be interested in reviewing the results of our law training survey. The data is available upon request.

Additionally, the Teaching, Training, and Careers Committee has compiled many useful teaching resources.

Several AP-LS professionals have donated sample application materials for internship, postdoctoral fellowship, and faculty positions, which are available for download. Thanks to the named and anonymous professionals who contributed these samples.

The AP-LS Student Committee hosts a webinar series featuring different AP-LS professionals presenting on topics of interest to student affiliates. Recorded past webinars are available on our unofficial website, and announcements about upcoming webinars are made via Facebook and Twitter.

Check out our interviews with professionals in the field, which cover a wide range of professional development topics.

Resources specifically for undergraduate students Current undergraduate students interested in a career in psychology and law should review the page Careers in Psychology and Law, which provides an overview of the field, different specialty areas, and various training routes.

Many of the graduate programs in psychology and law (but not all) are featured in the guide to graduate programs in forensic and legal psychology, compiled by the Teaching, Training, and Careers Committee.

Students from underrepresented groups who are interested in gaining more research experience to make themselves more competitive for graduate school should check out the Minority Affairs Committee's Access Path to Psychology and Law Experience (APPLE) program.

