---
title: Resources for Teaching Psychology and Law
draft: true
---

::: {.panel-tabset}
## Teaching Materials for Undergraduate Psychology and Law

Edie Greene and Erica Drew have collected information intended for instructors of undergraduate courses in psychology and law. As interest in the field has grown, so too has the availability of materials that instructors can use to enhance students' experiences and deepen their understanding of core concepts, theories and practices in psychology and law. The goal is to gather these diverse materials and make them easily accessible to instructors. Download the PDF (416KB).

["Activities for Teaching Psychology and Law: A Guide for Instructors"](https://www.apa.org/pubs/books/4311034) by Zelechoski, Wolbransky, and Riggs Romaine, offers a wide variety of such activities for courses in psychology and law. The activities incorporate individual and group work, videos, reading materials, classroom discussions, homework assignments, and lots of interactive exercises.

Many editions of the [AP-LS Newsletter](../newsletter) include a column titled "Teaching Techniques."

## Teaching Techniques

The Teaching Techniques column, sponsored by the AP-LS Teaching, Training and Careers Committee, appears in the AP-LS newsletter. The column offers useful ideas for those who teach (or who plan to teach) courses in psychology and law, forensic psychology or more specialized areas of legal psychology. In the column you can find activities, simulations and demonstrations that engage students in the learning process and help professors to teach important content in psychology and law.

The column editors welcome your comments, ideas, suggestions or submissions. We are especially interested in articles describing techniques that promote active learning in Psychology and Law. Please send submissions, questions or ideas for articles to any of the four editors:

Chief Editor: Mark Costanzo, Claremont McKenna CollegeCo-editor: Allison Redlich, University of AlbanyCo-editor: Beth Schwartz, Randolph CollegeCo-editor: Jennifer Groscup, Scripps College  
The following article by Wendy Heath appeared in the winter 2013 edition of the AP-LS News.

### Past Teaching Techniques Columns

Berman, G. L., & Platania, J. (2007, Fall) (PDF, 557KB). Deliberating the benefits of learning through focus groups.

Bornstein, B. H. (2006, Fall) (PDF, 438KB). Creating witnesses to teach about witnesses: A classroom demonstration.

Bottoms, B. L. (2006, Summer) (PDF, 458KB). Illustrating minority and majority influences through a jury simulation exercise.

Callahan, L. (2008, Fall) (PDF, 383KB). A sociologist looks at the field of forensic psychology.

Edens, J. F. (2008, Winter) (PDF, 507KB).  “Pretend you have a mental disorder”: Using a malingering simulation to illustrate important topics in forensic evaluation and experimental design

McCauley, M. (2007, Summer) (PDF, 449KB). Using writing assignments when teaching psychology and law.

MacLin, M. K. (2006, Winter) (PDF, 277KB). Implementing a mock crime, investigation and trial in your psychology and law course.

O’Connor, M., & Groscup, J. (2008, Summer) (PDF, 590KB). “Who’s your daddy (or mommy)?”: Teaching psychology and law through biography.

Schwartz, B. (2009, Summer) (PDF, 397KB). Developing a course on the issue of child abuse with a global perspective.

Wygant, D. (2011, Winter). (PDF, 319KB) All rise: Taking psychology outside of the classroom and into the courtroom
:::

## Online Teaching Resources
Internet resources that may aid instructors of classes in psychology and law include:

-   [Society for the Teaching of Psychology (Div. 2)](https://teachpsych.org/)

-   [Resources for the Teaching of Social Psychology: Psychology in the Courtroom](http://jfmueller.faculty.noctrl.edu/crow/courtroom.htm)

## Articles on Teaching in Psychology and Law 

Refer to the following articles for more suggestions about teaching classes in psychology and law. (This list is taken from the references of the first two listed articles.)

Anderson, D. (1992). Using feature films as tools for analysis in a psychology and law course. Teaching of Psychology, 19, 155-157.

Fass, M.E. (1999). A forensic psychology exercise: Role playing and the insanity defense. Teaching of Psychology, 26, 201-203.

Fulero, S., Greene, E., Hans, V., Nietzel, M., Small, M., & Wrightsman, L. (1999). Undergraduate education in legal psychology. Law and Human Behavior, 23, 137-153.

Greene, E. (1987). An undergraduate course in psychology and the law. Teaching of Psychology, 14, 238-239

Liss, M. (1992). Psychology and law courses: Content and materials. Law and Human Behavior, 16, 463-471.

Miller, L. (1997). Teaching about repressed memories of childhood sexual abuse and eyewitness testimony. Teaching of Psychology, 24, 250-255.

Ogloff, J., Tomkins, A., & Bersoff, D. (1996). Education and training in psychology and law/criminal justice. Criminal Justice and Behavior, 23, 200-235.

Otto, R., & Fulero, S. (2006). Integrating psychology and law into undergraduate instruction. Observer (Association for Psychological Science), 19, retrieved from http://www.psychologicalscience.org/observer/getArticle.cfm?id=1919

Perry, N., Huss, M., McAuliff, B., & Galas, J. (1996). An active-learning approach to teaching the undergraduate psychology and law course. Teaching of Psychology, 23, 76-81.

Schumacher, J.E., & Brodsky, S.L. (1988). The mock trial: An exploration of applications and dynamics in interdisciplinary training. Law and Psychology Review, 12, 79-93.

Schwarzmueller, A. (2006). Critiquing media portrayals of forensic professionals: A project for students. Teaching of Psychology, 22, 205-207.

Small, M. (1993). Legal psychology and therapeutic jurisprudence. St. Louis University Law Journal, 37, 675-700.

Swenson, E. (1983). Incorporating law into the undergraduate psychology curriculum. Teaching of Psychology, 10, 119-120.

Thagard, P. (2006). Evaluating explanations in law, science, and everyday life. Current Directions in Psychological Science, 15, 141-145.

Werth, J.L., Harvey, J., McNamara, R., Svoboda, A., Gulbrandson, R., Hendren, J., et al. (2002). Using controversial mock trials in Psychology and Law courses: Suggestions from participants. Teaching of Psychology, 29, 20-24.
