---
title: |
  All Rise: Taking Psychology Outside of the Classroom and Into the Courtroom
draft: true
---

The following article by Dr. Dustin Wygant appeared in the Winter 2011 edition (PDF, 356KB) of the AP-LS newsletter

College students seem to be naturally drawn to forensic psychology, often because of the subject’s rather unrealistic depiction on various television shows such as Criminal Minds, Law & Order SVU, and Profiler. I recall the sighs on the first day of my PSY 466 Forensic Psychology course when I burst the collective bubble in the room by telling my students that in my work as a forensic psychologist I have never once assisted in the capture of a serial killer or “profiled” a criminal suspect for the police. “This is not what we typically do in our roles as forensic psychologists” I told my students. “Well, what do you do then?” a student asked. “I’ll show you.” I replied.

Today’s students want to experience the subject, not just learn about it during a lecture. Incorporating experiential exercises into our classes can only help to bring our subjects to life (and likely our students as well). Those of us fortunate enough to teach courses on forensic psychology enjoy the benefit of having an interesting subject- the intersection of psychological science and legal jurisprudence. While forensic psychology is deeply rooted in the empirical and doctrinal traditions and theories of both psychology and law, it is also a subject that has real implications everyday- namely the application of psychological principles in our legal system. As such, we have the ability to take our concepts and theories and discuss or demonstrate their use in actual legal settings. Moreover, courts (and trials), by their very nature are enticing and hold our interest. While teaching Forensic Psychology this past fall, I developed an exercise to bring the concepts in the course to life for my students. This exercise, which culminated in a field trip to our local Kentucky Circuit Courthouse incorporated many of the key concepts I covered in the course: Voir Dire and the psychology of juries, the foundations of psychological opinions in the court, forensic psychological assessment, competency to stand trial, criminal responsibility, the relevance of psychological testing and psychiatric diagnosis in the court, malingered psychopathology, and finally, expert testimony.

I was fortunate to meet our county’s Circuit Judge, the Honorable William G. Clouse early in my tenure at Eastern Kentucky University. It certainly helped that he happened to be a distinguished alumnus of EKU and was more than willing to help his alma mater. Judge Clouse was gracious enough to allow my class unfettered access to his courtroom for a field trip this past November, during which my students observed oral arguments pertaining to the insanity defense for a murder trial. After being seated in the courtroom, the bailiff said those magical words, “All rise” and the experience became real to my students. But I’m getting ahead of myself. How did this all come about?

Several months earlier, when I was planning out my fall semester, an idea came to me that it would be interesting to take my students on a fieldtrip to the local courthouse to meet a judge. Initially, I thought it would be fun for the students to hear Judge Clouse give his perspective on several topics pertaining to the course (e.g., jury selection, insanity...). A thought came to me, however, that it would be much more interesting (and fun) to have the students observe me providing expert testimony about a case. I had worked for several years in a forensic practice before becoming a full time professor, and I had plenty of case materials to reference.

I immediately thought of one of my previous criminal cases; one involving the insanity defense in a murder trial. The case took place several years earlier in Ohio (which employs the M’Naghten rule as its insanity defense). The defendant in this case was clearly mentally ill (persecutory delusions), but also exhibited substantial evidence of malingered hallucinations throughout his incarceration and during the evaluation. Despite his history of mental illness, the defendant showed clear evidence of understanding the wrongfulness of his actions (e.g., evaded police detection, disposed of the weapon...). However, now that I am in Kentucky, which incorporates both the cognitive and volitional components of insanity, I reasoned that this defendant might have had a better chance with the insanity defense. Having settled on this case, I thought about which side I would argue in court. The prosecution’s position was that the defendant was malingering mental illness and knew the wrongfulness of his actions at the time of the offense. The defense reasoned that despite his malingering during the evaluation, the defendant had a longstanding history of mental illness, which substantially impaired his ability conform his behavior to the requirements of law (Kentucky Revised Statute §504.020). Given the facts of the case (coupled with my ability to rewrite history in whatever form I wanted since I already had to alter the basic facts of the case to preserve confidentiality), I reasoned that I could make a strong argument for either position. It struck me then, that this situation might be beneficial if I could get another person on board and have a “battle of the experts.” Rather than trying to convince a colleague to participate, I thought that this might be an opportunity to extend the exercise to one of my graduate students, Jaime Anderson, who was my teaching assistant for the class. Jaime was in the process of applying to doctoral programs in clinical forensic psychology and I reasoned that participation in this exercise would be a great experience to discuss in her personal statement. At this point, I had my case selected and an opposing expert witness; now all I needed were attorneys to get on board to complete the experience. Shortly thereafter, by chance I met a faculty member in the Government Department who was also the faculty mentor for the Mock Trial program at EKU. It occurred to me that this would once again be a great opportunity to get students involved, particularly ones interested in future careers as attorneys. I arranged it with the mock trial coach that I would get four mock trial students who had experience with the program and would be interested in learning more about forensic psychological assessment and expert testimony. For their efforts and considerable hard work on this project, each of the four students received one credit hour of independent study. The mock trial students were randomly divided into pairs to work as the prosecution and defense.

Having the major players in place, I set out prepare the case materials that the mock trial students would use to draft their arguments. I took the police investigation report from the original case, which took place in northeast Ohio three years earlier and revised it to set the crime up locally in Richmond, Kentucky during the past year. Having a seven page police report allowed for sufficient details from the initial interviews with the witnesses to establish information about the defendant’s mental status near the commission of the instant offenses. I then developed a detailed account of the defendant’s mental health in the jail, including notes from the jail psychiatrist, observations by the jail staff, and consultation notes from the consulting jail psychologist. Finally, I developed two forensic evaluations, the first coming from the Kentucky Correctional Psychiatric Center (KCPC), which handles the initial court-ordered forensic evaluations for the Circuit courts throughout Kentucky. I selected my graduate student as the prosecution’s expert and author of the report from KCPC. I then took my original report and revised it as the defense’s second opinion evaluation. The final two documents that were provided to the mock trial students included a copy of my curriculum vitae and one that I drafted for my graduate student. I deliberately selected my graduate student’s educational background and expertise in the field of forensic psychiatry to see if there was any effect of a psychiatrist offering expert testimony versus a clinical psychologist. With the police report, mental health records, two forensic evaluations, and CVs in place, the mock trial students had everything they needed to draft their arguments and positions for the case.

The mock trial case involved a young man who was charged with murdering one of his friends before traveling on foot to his former employer, where he shot his former boss, however, he did not fatally wound him. As I mentioned earlier, there was clear evidence that the defendant malingered symptoms of mental illness. Psychological testing in both evaluations, including the Minnesota Multiphasic Personality Inventory-2 (MMPI-2; Butcher et al., 2001), Miller Forensic Assessment of Symptoms Test (M-FAST; Miller, 2001), Structured Inventory of Reported Symptoms (SIRS; Rogers et al., 1992), and the Test of Memory Malingering (TOMM; Tombaugh, 1996) were all consistent with exaggerated symptoms of psychosis and memory impairment. Moreover, the defendant was recorded talking with his mother on the telephone while in jail, during which she instructed him to “play a little crazy.” In the mental status sections of each report, both examiners also noted inconsistencies in the defendant’s report of psychotic symptoms, as well as atypical and extremely bizarre hallucinations. However, there was also clear evidence that the defendant displayed paranoid delusional beliefs prior to the offense and long before his current legal involvement. Indeed, the defendant was evaluated as an adolescent, during which a psychologist concluded that he was exhibiting premorbid symptoms of a thought disorder. Both forensic reports had similar diagnostic conclusions, with the prosecutor’s report diagnosing the defendant with Malingering, Psychotic Disorder Not Otherwise Specified, Alcohol and Cannabis Abuse, and Personality Disorder Not Otherwise Specified with Paranoid Features, while the defense expert concluded Delusional Disorder Persecutory Type, Malingering, and Alcohol and Cannabis Abuse. The major difference between the two reports was that the prosecution expert concluded that malingering was the primary diagnosis and her forensic opinion regarding insanity was such that if he was currently malingering psychosis it was unclear if he was acutely mentally ill during the commission of the offenses. The defense expert concluded that while there was evidence of malingered auditory and visual hallucinations, there was sufficient evidence to diagnose the defendant with a Delusional Disorder based on the timeline of his mental status. Consequently, I concluded that given the defendant’s intense paranoid delusions at the time of the offense, he felt compelled to commit the crime and met the statutory requirements for an insanity defense. I purposefully constructed similar diagnostic conclusions between the two reports so that the mock attorneys would have to argue differences in emphasis regarding which diagnosis was primary in terms of guiding the forensic opinion about insanity.

With both reports and supporting documents in place, the final piece was the selection of the jury panel. I initially thought that I would simply select the students for the jury and script the oral arguments in such a manner as to make it clear which side had clearer evidentiary support. However, one of the students in my class approached me after one lecture when I first told them about the experience and offered a suggestion. This student recommended that we have a voir dire session prior to the field trip so that each side could select potential “jurors” more in line with their positions. I thought this was a great idea and took it one step further by having my mock trial attorneys each develop a one-page juror questionnaire in order to obtain background information for questioning. Each side developed the questionnaire and I administered it to my class after assigning each student a jury number.

 The mock trial students compiled the results and made initial selections about exclusions based on cause (one of the students knew someone in the class on a personal level) as well as peremptory challenges. The mock trial students visited my class during the session before the field trip and called on the students by juror number with follow-up questions. I served as the judge to moderate the jury selection. Many of the questions focused on attitudes about mental illness and gun control, however, some of the questions involved aspects of socioeconomic status (e.g., examination of the student’s shoes), illustrating points made by Greene and Heilbrun (2011) in the course’s text about implicit personality characteristics that attorneys rely upon when selecting jurors. The mock trial students selected 12 students and 2 alternate jurors.

On the day of the field trip, the students showed up after Judge Clouse had finished his daily docket. The bailiff took the 12 jurors and seated them in the jury room while brief opening statements were made in the courtroom. For the purpose of this experience, we skipped many of the evidentiary procedures and pretrial motions that would have taken place and focused the session on the testimony of the two expert witnesses.

My graduate student, Jaime, began as the prosecution’s witness. Before she provided testimony regarding the case, she was questioned about her credentials and the prosecution petitioned the court to acknowledge her as an expert in forensic psychiatry. Jaime then proceeded with direct testimony from the prosecution. The prosecution established their line of questioning in a deductive manner by having Jaime discuss the results of the evaluation (i.e., psychological test results and clinical observations) that supported a conclusion of malingering. It was then argued that if the defendant was malingering so substantially during the evaluation that it would be difficult to support his claim of insanity during the commission of the offenses. Following direct examination, Jaime underwent cross-examination by the defense attorney. This testimony focused on information excluded during the prosecution’s questions that pertained to the defendant’s history of mental illness.

After Jaime concluded her testimony, I was called to the stand as the defense expert. Similar to the initial testimony, I began by discussing my credentials before the defense petitioned the court to acknowledge me as an expert in forensic psychological assessment. During direct testimony with the defense attorney, I established a time line for the defendant’s mental status, beginning with an evaluation that was completed during his adolescence and suggested that he exhibited premorbid indications of thought disorder. Following this, I discussed records and interviews with individuals who could substantiate the defendant’s mental status closer to the time of the offense. This inductive manner of questioning was in stark contrast to the prosecution’s approach and demonstrated to the students how attorney’s on either side could construct an argument with different conclusions using basically the same information. Following direct examination, the prosecuting mock trial student performed cross examination, during which he argued that my conclusions about the defendant’s mental status during the instant offense was heavily influenced by his own statements and lacked credibility due to his malingered psychopathology during the evaluations.

Following both testimonies, the prosecution and defense were each allowed five minutes for a closing argument before the student jurors retired to the jury room to deliberate. Given the time constraints involved since the testimony and closing statement took approximately an hour and a half to conclude, the jurors were instructed to deliberate for 15-20 minutes and base their conclusion of guilty or not guilty by reason of insanity on a majority rule versus a unanimous decision. After 15 minutes of deliberation, the jurors returned to the courtroom and concluded that the defendant was not guilty by reason of insanity with an 8-4 decision.

The fieldtrip was an unequivocal success. Some of the student reactions included, “Overall, I think this was an extremely positive learning experience. We were able to see how forensic psychologists interact in the courtroom, and how their testimony is used in the deliberation process, as well as how jury selection and deliberation occurred.” Another student remarked, “The mock trial provided a truthful look at the court process, the role of the forensic psychologist, and, in this particular instance, how sanity can be interpreted by both the prosecution and defense to sway jury members. This is especially important since an adversarial nature is the basis for the legal system.” Moreover, other students remarked ,”There is little that reading a textbook can compare to real world simulations” and “I felt as though this experience was a great way to tie all aspects of the adversarial nature of a trial, jury psychology, and what it is like to be an expert witness that we learned throughout the semester.” Most of all, the field trip was fun and everyone involved benefitted from the experience. It was a great way to bring to life so many of the course’s ideas in one experience and was hopefully one that the students will remember long after the course.

### Author Note
Dustin B. Wygant, Ph.D. is an Assistant Professor of Psychology at Eastern Kentucky University. He is a licensed clinical psychologist in Kentucky and Ohio and regularly consults with the University of Cincinnati Division of Forensic Psychology in addition to operating his own forensic consultation company. All materials used in this teaching exercise are available for review and use. Please contact Dr. Wygant 521 Lancaster Avenue, Richmond, KY 40475. Fax: (859) 622-5871.

### References
Butcher, J.N., Graham, J.R., Ben-Porath, Y.S., Tellegen, A., Dahlstrom, W.G., & Kaemmer, B. (2001). MMPI-2: Manual for administration and scoring (Rev. ed.). Minneapolis, MN: University of Minnesota Press.

Greene, E., & Heilbrun, K. (2011). Wrightsman’s Psychology and the Legal System (7th Ed.). Belmont, CA: Wadsworth Cengage Learning.

Kentucky Revised Statute §504.020. Mental illness or retardation.

Miller, H.A. (2001). M-FAST: Miller Forensic Assessment of Symptoms Test professional manual. Odessa, FL: Psychological Assessment Resources, Inc.

Rogers, R., Bagby, R. M., & Dickens, S. E. (1992). Structured Interview of Reported Symptoms: Professional Manual. Odessa, FL: Psychological Assessment Resources.

Tombaugh, T. N. (1996). Test of Memory Malingering (TOMM). New York: Multi-Health Systems Inc.