---
title: Diversity Travel Awards
date: last-modified
description: Provides travel awards to students from underrepresented groups who are presenting research at the American Psychology-Law Society Conference. 
categories: 
  - Students
  - Undergraduate
  - Graduate
  - Conference Travel
  - Diversity
  - BRIDGE Committee
submission-info:
  sponsor: AP-LS BRIDGE Committee
  deadline: "January 15, `r format(Sys.Date(), '%Y')`"
links:
- icon: envelope-at
  name: Contact
  url: "mailto:ann38@drexel.edu"
- icon: send
  name: Apply here
  url: "https://ssp.qualtrics.com/jfe/form/SV_ePbaazCXWwNreZ0"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../../assets/apls_functions.R")
```

<hr>


:::{.panel-tabset}

## Description

As part of an initiative to increase diversity within AP-LS, the BRIDGE Committee will provide travel awards to students from underrepresented groups who are presenting research at the American Psychology-Law Society Conference.

Seven competitive travel awards in the amount of $500 will be given each year.

Applications will be judged by members of the BRIDGE Committee. Awards will be made on a competitive basis, with consideration given to applicants' financial need.

::: callout-caution
Please be aware that students can only receive funding from one BRIDGE program/award per year.

For more information about the Diversity Travel Award program, please contact the [BRIDGE Travel Award program chair](mailto:ann38@drexel.edu).

:::

## Eligibility

Current graduate and undergraduate students from underrepresented groups (i.e., racial and ethnic minorities, first-generation college students, LGBTQIA individuals, and students with disabilities) may apply for this award.

Applicants must be a [Student Affiliate]("../../membership/membership.qmd") member of AP-LS and be presenting research at the annual conference.

:::{.callout-note} 
These awards are intended to increase diversity at the conferences, especially among racial and ethnic minorities; in addition, the BRIDGE will consider proposals from first-generation college students, LGBTQIA individuals and physically disabled students. 
:::

## How to Apply

Award submissions will be accepted from September 15 to January 15 annually.

::: callout-tip
## A complete application must include the following:

1.  A cover letter which provides contact information for the applicant and specifies the applicant's eligibility for the award as a member of an underrepresented group.

2.  An approximately two-page (double-spaced) statement that describes:

    1.  the student's professional goals

    2.  the presentation(s) they will be making at the conference

    3.  how attending the conference will benefit the student

    4.  their financial need for the award (including a description of other travel funds available to the student)

3.  A completed W-9 (U.S. citizen) or W-8 (non-citizen) tax form.

4.  A letter of support from a faculty mentor addressing the importance of presenting the project at the AP-LS conference for the student's advancement in their Psychology and Law career. Letters must be emailed to the [BRIDGE Travel Award program chair](https://www.apadivisions.org/division-41/leadership/committees/representation-inclusion-diversity) no later than January 15.
:::

<a class="btn btn-primary" href="https://ssp.qualtrics.com/jfe/form/SV_ePbaazCXWwNreZ0" role="button">Link to Apply</a>

## Award Recipients

Award recipients will be notified by February prior to the conference and the travel award will be disbursed by reimbursing expenses following the conference.

::: {callout-note}
## Recipients will be required to:

1.  Attend a BRIDGE reception during the conference during which they will be publicly recognized
2.  Maintain receipts to document their expenses at the conference
:::

:::
