---
title: Dissertation Awards
date: last-modified
description: The American Psychology-Law Society confers Dissertation Awards for scientific research and scholarship that is relevant to the promotion of the interdisciplinary study of psychology and law. Students who complete dissertations involving basic or applied research in psychology and law, including its application to public policy, are encouraged to apply for these awards. Only students who have completed their dissertations in the current calendar year are eligible to apply. First-, second- and third-place awards are conferred, and winners will be invited to present their research at the AP-LS Annual Conference.
categories: 
  - Students
  - Graduate
  - Dissertation
---

The award supports students who complete dissertations involving basic or applied research in psychology and law, and the winners will be invited to present their research at the annual AP-LS conference.

<a class="btn btn-primary btn-lg" href="https://awards.ap-ls.org/default.asp" role="button">Apply Here</a>

```{=html}

  <!-- Description info -->

<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Description
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        <p>The American Psychology-Law Society confers Dissertation Awards for scientific research and scholarship relevant to the promotion of the interdisciplinary study of psychology and law. Students who complete dissertations involving basic or applied research in psychology and law are encouraged to apply for these awards. First, second, and third-place awards will be conferred; winners will be invited to present their research at the annual AP-LS conference and receive a cash award.
 </p>
      </div>
    </div>
  </div>
  
    <!-- Eligibility info -->

  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Eligibility
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
      <p>To be eligible for the award, you must be a member of AP-LS and have defended your dissertation during the calendar year of the submission deadline (e.g., if the deadline for submissions is December 31, 2015, then you must have defended your dissertation in 2015). 
</p>
<p> Note: You do not need to have graduated by December 31.</p>
      
 </div>
    </div>
  </div>
  
    <!-- How to apply info -->

  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        How to Apply
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        <p>To apply for the Dissertation Awards, please attach the following items in an [email](mailto:aplsdissertations@gmail.com) by December 31: 
</p>
    
        <ul style="margin-left: 5px;">
      <li><p> the dissertation as it was submitted to the student’s university (in Word or PDF);</li></p> 
       <li><p> the dissertation with all author, advisor, and school identifying information removed (in Word or PDF); </li></p> 
        <li><p> a signed letter of support (on letterhead) from the dissertation advisor. </li></p> 
         </ul>

      <p> These can be submitted via one email from the student, or via separate emails from the student and advisor.
</p>

<p> For more information, please contact the chair of the [Dissertation Awards Committee](https://www.apadivisions.org/division-41/leadership/committees).
</p> 
<p><strong> Annual deadline: December 31
</strong></p> 
                    </div>
      </div>
    </div>
  </div>
  
      <!-- Past Recipients -->

  <div class="accordion-item">
    <h2 class="accordion-header" id="headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
       Past Recipients
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
 
```
+------+------------------------+-------------------------------+------------------------------------+
| Year | 1st place              | 2nd place                     | 3rd place                          |
+======+========================+===============================+====================================+
| 2019 | Christine Shahan Brugh | Dylan T. Gatner               | Alicia Nijdam-Jones                |
+------+------------------------+-------------------------------+------------------------------------+
| 2018 | Lucy Guarnera          | Pia Hollerbach                | Rachel Greenspan                   |
+------+------------------------+-------------------------------+------------------------------------+
| 2017 | Nathalie Brackmann     | Melissa Colloff               | Lauren Kois                        |
+------+------------------------+-------------------------------+------------------------------------+
| 2016 | Evan McCuish           | Caitlin Cavanaugh             | Kelsey Henderson                   |
+------+------------------------+-------------------------------+------------------------------------+
| 2015 | Skye Stephens          | Laura White                   | Alana Krix                         |
+------+------------------------+-------------------------------+------------------------------------+
| 2014 | Anthony Perillo        | (tie) Miko Wilford & Misun Yi | Jeffrey Kukucka                    |
+------+------------------------+-------------------------------+------------------------------------+
| 2013 | Taeko Wachi            | Rebecca Weiss                 | Heather Butler                     |
+------+------------------------+-------------------------------+------------------------------------+
| 2012 | Kaitlyn McLachlan      | Ekaterina Pivovarova          | Jessica Salerno                    |
+------+------------------------+-------------------------------+------------------------------------+
| 2011 | Annelies Vredeveldt    | Jay P. Singh                  | Julia Clara Busso Kennard          |
+------+------------------------+-------------------------------+------------------------------------+
| 2010 | Samantha Schwartz      | Caroline Crocker              | Ashley Christiansen                |
+------+------------------------+-------------------------------+------------------------------------+
| 2009 | Tarika Daftary-Kapur   | Gianni Pirelli                | Bethany Young                      |
+------+------------------------+-------------------------------+------------------------------------+
| 2008 | Margaret C. Stevenson  | Laura G. Kirsch               | Melanie R. Farkas & Lindsay Malloy |
+------+------------------------+-------------------------------+------------------------------------+
| 2007 | Jeffrey Haun           | Kathryn Modecki               | Tracy Fass                         |
+------+------------------------+-------------------------------+------------------------------------+
| 2006 | Amy Leach              | Jessica Klaver                | Jessica Meyer                      |
+------+------------------------+-------------------------------+------------------------------------+
| 2005 | Tara Mitchell          | Lisa Chraznowski              | Lora Levett &\                     |
|      |                        |                               | Greg Kramer                        |
+------+------------------------+-------------------------------+------------------------------------+
| 2004 | Jodi Viljoen           | Candice Odgers                | Martin Hildebrand                  |
+------+------------------------+-------------------------------+------------------------------------+
| 2003 | Virginia Cooper        | Teri Forrest                  | Mary Ann Campbell & Alexis Kennedy |
+------+------------------------+-------------------------------+------------------------------------+
| 2002 | Jennifer Groscup       | Tamara Haegerich              | Gina Vincent &\                    |
|      |                        |                               | David DeMatteo                     |
+------+------------------------+-------------------------------+------------------------------------+
| 2001 | Mark Phillips          | Christian Meissner            | Eve Brank                          |
+------+------------------------+-------------------------------+------------------------------------+
| 2000 | Bradley McAuliff       | Lyn Castrianno                | Kimberly Brown                     |
+------+------------------------+-------------------------------+------------------------------------+
| 1999 | Jennifer Skeem         |                               | Dan Krauss                         |
+------+------------------------+-------------------------------+------------------------------------+
| 1998 | Joanna Pozzulo         | Jennifer Robbennolt           | Dennis Stolle                      |
+------+------------------------+-------------------------------+------------------------------------+
| 1997 | David Glass            | Stephen Anderer               | Richard Redding                    |
+------+------------------------+-------------------------------+------------------------------------+
| 1996 | Kimberly Lonsway       | Charles R. Mullin             | Phyllis B. Gerstenfeld             |
+------+------------------------+-------------------------------+------------------------------------+
| 1995 | Lori Beth Frank        | Mindy Mechanic                | Maithilee K. Pathak                |
+------+------------------------+-------------------------------+------------------------------------+
| 1994 | Margaret Kovera        | Karen Leslie Steinberg        | Nancy Schneider                    |
+------+------------------------+-------------------------------+------------------------------------+
| 1993 | Ann Tobey              | Doug Narby                    |                                    |
+------+------------------------+-------------------------------+------------------------------------+
| 1992 | Bette Bottoms          | \                             | Cathy Carter                       |
+------+------------------------+-------------------------------+------------------------------------+
| 1991 | Barry Rosenfeld        |                               |                                    |
+------+------------------------+-------------------------------+------------------------------------+
| 1990 | James Ogloff           | Regina Schuller               | Mark Small                         |
+------+------------------------+-------------------------------+------------------------------------+
| 1989 |                        |                               |                                    |
+------+------------------------+-------------------------------+------------------------------------+
| 1988 | Patricia Frazier       |                               |                                    |
+------+------------------------+-------------------------------+------------------------------------+
| 1987 | Brian Cutler           |                               |                                    |
+------+------------------------+-------------------------------+------------------------------------+
| 1986 | Roselle Wissler        |                               |                                    |
+------+------------------------+-------------------------------+------------------------------------+
| 1985 | Nancy Brekke           | Carol Krafka                  |                                    |
+------+------------------------+-------------------------------+------------------------------------+
| 1984 | Daniel Linz            |                               |                                    |
+------+------------------------+-------------------------------+------------------------------------+
| 1983 | Sarah Tanford          | Edie Greene                   |                                    |
+------+------------------------+-------------------------------+------------------------------------+

```{=html}
<div class="card text-primary bg-secondary mb-3" style="max-width: 20rem;">
<div class="card-header">Contact info</div>
  <div class="card-body">
    <p class="card-text">AP-LS Dissertation Award Committee<br>aplsdissertations@gmail.com</p>
  </div>
</div>
```
