---
title: Outstanding Teaching and Mentoring in the Field of Psychology and Law
date: last-modified
description: The American Psychology-Law Society confers an award for Outstanding Teaching and Mentoring in the Field of Psychology and Law to recognize teaching excellence in a variety of contexts.
categories: 
  - Teaching
  - Awards
  - Early Career Professionals
  - Mentoring
---

Recognizes teaching excellence in the field of psychology and law.

<a class="btn btn-primary btn-lg" href="https://awards.ap-ls.org/default.asp" role="button">Apply Here</a>

```{=html}

    <!-- Description -->

<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Description
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        <p>Every year Div. 41 (American Psychology-Law Society) confers two awards for Outstanding Teaching and Mentoring in the Field of Psychology and Law to recognize teaching excellence in a variety of contexts: Outstanding Teaching and Mentoring Award and the Early Career Teaching and Mentoring Award. The winner of the awards will be announced at the annual meeting of the American Psychology-Law Society.</p>
    <ul style="margin-left: 5px;">
<li><p> In even-numbered years (e.g., 2016, 2018), the award will be given to a teacher/mentor from a program/department that is undergraduate-only or MA-terminus (category 1).</li></p>
<li><p> In odd-numbered years (e.g., 2015, 2017), the award will be given to a teacher/mentor from a program/department that is doctoral-granting or postdoctoral granting; including law schools, medical schools, and non-university positions such as hospitals, clinics or other organizations. The primary requirement is that the recipient have taught/mentored graduate and/or postdoctoral students (category 2).
</li></p>
</ul>

      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Eligibility
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
      <p>Nominees should be persons who have made substantial contributions to student training in the field of psychology and law.</p>

<p>To be eligible for the <strong>Outstanding Teaching and Mentoring Award,</strong> an individual must have held a PhD or JD degree for at least eight years, and must have been teaching and/or mentoring students in psychology and law for at least eight years.</p>

<p>To be eligible for the <strong>Early Career Teaching and Mentoring Award,</strong> an individual must have held a PhD or JD degree for seven years or less years, and must have been teaching and/or mentoring students in psychology and law for seven years or less (i.e., AP-LS Early Career Professionals).</p>

<p>Nominees cannot apply for both awards. Those who obtained their degree eight years or more from the application year are only eligible for the Outstanding Teaching and Mentoring Award, and those who obtained their degree seven years or less are only eligible for the Early Career Teaching and Mentoring Award.</p>
      
 </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        How to Apply
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        
<ul style="margin-left: 5px;">
      
            <li><p> nominee’s statement (one–two pages) of teaching/mentoring philosophy, goals, and accomplishments, especially as related to the field of psychology and law (Please state which award you are applying for (Outstanding Teaching and Mentoring Award or the Early Career Teaching and Mentoring Award) and how you meet the criteria for that award.)</p></li>
              <li><p> abbreviated curriculum vitae (three pages maximum)</p></li>
                <li><p> summarized student evaluations; (student evaluations should be recent and include at least 3 years)</p></li>
                  <li><p> at least one, but no more than three, supporting letters from peer reviewers or students</p></li>
                    <li><p> other relevant documentation such as descriptions of current and past student achievements; mentoring in one-on-one teaching contexts (e.g., advising, clinical supervision); teaching in the community (e.g., workshops that bring psychology and law to applied audiences); teaching-related committee work or scholarship; development of new curricula, courses, course materials or instructional methods
</p></li>
            
 </ul>
 <p>Self-nominations are encouraged.</p>

<h4> Contact information</h4>
Nominations packets should be emailed to the current chair of the  [Teaching, Training and Career Committee] (https://www.apadivisions.org/division-41/leadership/committees)
<h4> To be awarded
</h4>
Recipients of the awards will receive $500 and a plaque at the AP-LS conference.

<p><strong>Annual deadline: December 15</strong></p>

                    </div>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
       Past Recipients
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
```
| Year | Outstanding Teaching and Mentoring Award              | Early Career Award                |
|------------------------|------------------------|------------------------|
| 2020 | Garrett Berman (category 1)                           | Nesa E. Wasarhaley (category 1)   |
| 2019 | Eve M. Brank and Robert E. Cochrane (category 2)      | Cynthia J. Najdowski (category 2) |
| 2018 | Jennifer L. Groscup (category 1)                      | Tess M.S. Neal (category 1)       |
| 2017 | Monica K. Miller and Jennifer Robbennolt (category 2) |                                   |
| 2016 | Matthew Huss (category 1)                             | Amanda Zelechoski (category 1)    |
| 2015 | Jodi Quas (category 2)                                |                                   |
| 2014 | Bradley D. McAuliff (category 1)                      |                                   |
| 2013 | Roderick C.L. Lindsay (category 2)                    |                                   |
| 2012 | Amye R. Warren (category 1)                           |                                   |
| 2011 | Brian Bornstein (category 2)                          |                                   |
| 2010 | Mark Costanzo (category 1)                            |                                   |
| 2009 | Ronald Roesch (category 2)                            |                                   |
| 2008 | Edie Greene (category 1)                              |                                   |
| 2007 | N. Dickson Reppucci (category 2)                      |                                   |
| 2006 | Bette Bottoms and Jim Ogloff                          |                                   |
| 2005 | Bette Bottoms and Jim Ogloff                          |                                   |
| 2004 | Margaret Bull Kovera                                  |                                   |
| 1996 | Gail Goodman (First time awarded)                     |                                   |

