---
title: AP-LS By-laws
date: last-modified
title-block-banner: "../../images/default-banner.svg"
toc: true
---
### Article I: Name and Purpose

1.  The name of this organization shall be: The American Psychology-Law Society (Society)/Division 41 of the American Psychological Association (Association).

2.  The purposes of the Society shall be to:

    a.  Advance the contributions of psychology to the understanding of law and legal institutions through basic and applied research;

    b.  Promote the education of psychologists in matters of law and the education of legal personnel in matters of psychology, including the appropriate use of psychologists in the legal system; and

    c.  Inform the psychological and legal communities and the general public of current research, educational, and service activities in the field of psychology and law.

### Article II: Membership

1.  There shall be six categories of members in the Society:

    a.  Full Members shall be those with doctorate degrees in Psychology or related discipline or a Juris Doctorate who join both the Association and the Society. Full Affiliates shall be those with doctoral degrees in Psychology or a related discipline or a Juris Doctorate who join the Society but do not join the Association.

    b.  Associates shall be those with master's degrees in Psychology or a related discipline or a terminal bachelors degree who join both the Association and the Society. Associates are eligible to vote after 5 consecutive years of Association membership (referred to as Five-Year Voting Associates). Associate Affiliates shall be those with master's degrees in Psychology or a related discipline or a terminal bachelors degree who join the Society but do not join the Association.

    c.  Early Career Professional Members shall be those within 10 years of receiving a doctoral degree in Psychology or related discipline or a Juris Doctorate who join both the Association and the Society. Early Career Professional Affiliates shall be those within 10 years of receiving a doctoral degree in Psychology or related discipline or a Juris Doctorate who join the Society but do not join the Association.

    d.  Fellows shall be Full Members who have been granted Fellow Status by the Association and Society. Distinguished Members shall be Full Affiliates who have been granted Distinguished Member status by the Society.

    e.  International Affiliates shall be Full Affiliates who join the Society and reside outside the United States.

    f.  Student Affiliates shall be undergraduate or graduate students who join the Society.

2.  Members from all six categories of membership are eligible to serve on Society committees.

3.  Full Members nominated for Fellow in the Society must provide evidence of unusual and outstanding contributions in the area of psychology and law. All candidates for Fellow must be endorsed by at least two Fellows of the Society. In addition, all candidates for Fellow must meet the requirements of the by-laws of the Association. Full Affiliates nominated for Distinguished Member in the Society must provide evidence of unusual and outstanding contributions in the area of psychology and law. All candidates for Distinguished Member must be endorsed by at least two Fellows or Distinguished Members of the Society.

4.  Minimum membership dues are set by vote of the Executive Committee and may be imposed on all members. Non-payment of dues for two consecutive years shall be considered as equivalent to resignation from the Society.

### Article III: Officers and Voting Members of the Executive Committee

1.  The officers of the Society and voting members of the Executive Committee shall consist of a President, a President-Elect, an Immediate Past-President, a Secretary, a Treasurer, three Members-at-Large, Division Representatives to the Council of Representatives of the Association (in numbers permitted by the Association), and a Student Committee Chair. Each shall perform the usual duties of the respective office and specific duties provided elsewhere in these By-Laws or assigned by the Executive Committee (see Article IV, Section 2 of these By-Laws).

    a.  President:

    > The President shall be the principal officer of the Society and shall in general supervise all of the business and affairs of the Society. The President shall preside at all meetings of the membership and of the Executive Committee and in general shall perform all duties incident to the office of President and such other duties as may be prescribed by the Executive Committee. The President shall be elected for a three-year term, serving the first year as President-Elect, the second year as President, and the third year as Immediate Past-President. Full Members and Full Affiliates, Fellows and Distinguished Members are eligible to serve as President. Full Members, Full Affiliates, Fellows and Distinguished Members, and Five-Year Voting Associates are eligible to vote in the election of President.
    >
    > In the absence of the President or in the event of the President's inability to act, the President-Elect shall perform the duties of the President and, when so acting, shall have all the powers of and be subject to all the restrictions upon the President. The President-Elect shall perform such other duties as from time to time may be assigned by the President or by the Executive Committee.

    b.  Treasurer

    > The Treasurer shall have charge and custody of and be responsible for all funds of the Society, receive and give receipts for monies due and payable to the Society, deposit all such monies in the name of the Society in such banks or other depositories as shall be selected by the Executive Committee, prepare an annual financial report and a budget for the upcoming year for the Society, and in general perform all duties incident to the office of Treasurer and such other duties as from time to time may be assigned by the President or by the Executive Committee. The Treasurer shall serve for a five-year term of office, this term being staggered with the term of the Secretary in such a manner as to provide continuity for the Executive Committee and the Society.
    >
    > Nothing in this Section shall be construed to bar collection by the Association or any other entity designated by majority vote of the Executive Committee of funds due and payable to the Society. When such collection occurs, the Treasurer shall have charge of ensuring ultimate deposit of such funds in the accounts of the Society and maintaining appropriate accounting of their receipt. Full Members and Full Affiliates are eligible to serve as Treasurer. Full Members, Full Affiliates, and Five-Year Voting Associates are eligible to vote in the election of Treasurer.

    c.  Secretary:

    > The Secretary shall keep the minutes of the meetings of the Executive Committee, be the custodian of the Society records, secure and review evidence concerning the qualifications of all candidates for membership or changes in membership status in the Society, maintain an annually-updated membership list, disseminate information regarding the Society's activities to the membership, and in general perform all duties incident to the office of Secretary and such other duties as from time to time may be assigned by the President or by the Executive Committee. The Secretary shall submit a budget for necessary operating expenses to the Executive Committee for approval, and shall have the authority to hire an Administrative Assistant according to the amount approved for such expenses. The Secretary shall serve for a three-year term of office, this term being staggered with the term of the Treasurer in such a manner as to provide continuity for the Executive Committee and the Society. Full Members and Full Affiliates are eligible to serve as Secretary. Full Members, Full Affiliates, and Five-Year Voting Associates are eligible to vote in the election of Secretary.

    d.  Members-at-Large:

    > One Member-at-Large shall oversee Research, Teaching, and Practice committees. One Member-at-Large shall be responsible for representing the Special Interest committees. One Member-at-Large shall be responsible for managing the Administration, Awards, and Communication committees. Members-at-Large may also take on other duties as assigned by the President, in consultation with the Executive Committee. Members-at-Large shall be elected by Society membership and shall serve terms of three years, these terms being staggered so that one Member-at-Large is elected each year. Full Members, Full Affiliates, Fellows and Distinguished Members are eligible to serve as Members-at-Large. Full Members, Full Affiliates, Fellows and Distinguished Members and Five-Year Voting Associates are eligible to vote in the election of Members-at-Large. In the event that a Member-at-Large is unable to complete his/her term, the President may appoint, with consultation of the Executive Committee, a member to complete the unexpired term of the predecessor in that office.

2.  There shall be Divisional Representatives to the Council of Representatives (Council) of the Association in numbers permitted by the Association. Representatives shall be elected for a three-year term of office. In the event that there is more than one Divisional Representative allotted by the Association, their terms will be staggered in such a manner as to provide continuity in representation to the Council. Full Members and Fellows are eligible to serve as Divisional Representatives. Full Members and Five-Year Voting Associates are eligible to vote in the election of Division Representatives. In the event that a Divisional Representative is unable to complete his/her term, the President may appoint, with consultation of the Executive Committee, a member to complete the unexpired term of the predecessor in that office.

3.  The Student Committee Chair is elected by the Student Affiliates in accordance with procedures set in the [Student Committee By-Laws](insert link).

Article IV: Committees

1.  The Committees of the Society shall consist of standing committees as provided by the By-Laws. The President, in consultation with the Executive Committee, may establish ad hoc committees and task forces to carry out the business of the Society or to accomplish particular tasks. No committee or task force shall have the authority of the Executive Committee in reference to amending, altering, or repealing the By-Laws; electing, appointing, or removing any officer of the Society; or amending or repealing any resolution of the Executive Committee; nor shall the appointment of any such committee and the delegation thereto of authority relieve the Executive Committee or any individual Executive Committee member of any responsibility imposed upon it by these By-Laws. In accordance with Article V, Section 7 of the By-Laws of the Association, all committees shall be subject to a review by the Association's Board of Directors.

2.  Executive Committee:

    a.  There shall be an Executive Committee of the Society, consisting of the President, the President-Elect, the Immediate Past-President, the Secretary, the Treasurer, the Divisional Representative(s) to the Council, three Members-at-Large, the newsletter editor, web page editor, the editors of the Society's journals, the book series editor, and the chair of the Student Committee of the Society. The newsletter editor, the editor of the Society's journals, the web page editor, and the book series editor are non-voting, ex-officio members of the Executive Committee. All chairs of Society committees are invited to attend Executive Committee meetings. Any vacancy occurring in the Executive Committee shall be filled by an appointment of the President, in consultation with the Executive Committee, to fill the unexpired term of the predecessor in that office.

    b.  In the conduct of Society business, the Executive Committee shall follow the procedural rules of Keesey's Modern Parliamentary Procedure.

    c.  For voting purposes, a quorum shall consist of more than 50% of the voting members of the Executive Committee.

    d.  The Executive Committee shall set and amend Society policy by majority vote of a quorum. Because the Association is organized under the laws of the District of Columbia, the Association and its divisions, including the Society, cannot make decisions in settings other than those in which all of the board members (or Executive Committee members) can hear one another speak on the topic to be decided. As such, Society business should be carried out using face-to-face, telephone, or web-based meetings whenever possible. If the Society conducts a vote over email, unanimous approval is required; unanimous approval means that every eligible voting member must respond and everyone must agree.

    e.  The Executive Committee shall meet at least twice annually at the Association's annual convention and the Society's annual conference. Other meetings may be held on the call of the President, by consensus of the Secretary and Treasurer, or by consensus of a simple majority of the Executive Committee. All outgoing and incoming members of the Executive Committee should be present at the annual meeting of the Executive Committee (held in conjunction with the Association's annual convention). With the consideration of new business, the President-Elect shall assume the office of President and the incoming Executive Committee shall take office. All members of the Executive Committee should also be present for the annual meeting of the Executive Committee held in conjunction with the Society's annual conference.

    f.  Executive Committee members, other than the journal editors and book series editor, shall not be paid for their services to the Society. Executive Committee members will be reimbursed for travel to Society executive meetings according to the reimbursement policies then in effect. For good cause shown, and with the prior approval of the President, an Executive Committee member shall be considered present at a meeting, and eligible to vote, if participating by conference call or other remote means.

Article V: Activities

1.  There shall be an annual Society conference at which scientific papers shall be presented and professional matters in the field of the Society's interest shall be discussed. In addition, the Society will prepare programming as Division 41 for the annual Association convention.

2.  The Society shall publish a newsletter and maintain a web page for purposes of coordinating and disseminating news relevant to the membership of the Society.

    a.  As a part of its mandate, the newsletter or web page shall publish the minutes of each Executive Committee meeting, the annual budget for the Society, announcements of the petition process as outlined in Article IV, Section 4(a) of these By-Laws, and final nominations for Society offices.

    b.  The editors of the newsletter and web page shall be nominated by the Nominations and Awards Committee, in consultation with the Publications and Communications Committee, such appointment subject to the approval of the Executive Committee. The editors shall be appointed to three-year terms and shall serve as ex-officio, non-voting members of the Executive Committee. By mutual consent of the newsletter editor or web page editor and the Executive Committee, the appointments may be extended for one additional three-year term, for a maximum of six years.

3.  The Society shall publish journals with the goal of disseminating results of research and scholarly writing in the area of psychology and law. The Editor of a Journal shall be nominated by the Nominations and Awards Committee, in consultation with the Publications and Communications Committee and the (Outgoing) Editor. The Nominations and Awards Committee shall provide a list of two or three eligible candidates to the Executive Committee for consideration. The appointment of an Incoming Editor is subject to the approval of the Executive Committee and shall be made at least 18 months prior to the end of an Editor's term. Beginning in January of an (outgoing) Editor's final year, the appointed candidate serves as an Incoming Editor for a one-year period. An Incoming Editor receives all new submissions and is mentored by the Editor. Following the one-year term as an Incoming Editor, an Editor serves a six -year term. In the last of this six-year term, an Editor serves as a mentor to the new Incoming Editor.

    An Editor assumes all Editor responsibilities during the six-year term. An Editor's term is non-renewable but may be extended for up to two-years by majority vote of the Executive Committee. The extension should occur only under extenuating circumstances. An Editor may resign early through written notification to the President or may apply to the Executive Committee for a leave-of-absence. An Editor's responsibilities include appointing the Associate Editors, Editorial Board, and Ad-Hoc Reviewers; soliciting manuscripts; managing the peer-review and publication processes; serving as a liaison with the publisher; reporting to the Executive Committee; representing the journal to all constituencies; and coordinating all other journal operations. An Editor takes a lead role in publication contract negotiations that occur during the Editor's term (all contracts must be approved by the Executive Committee). An Editor manages the journal's Editorial Budget and in so doing gives consideration to the needs of the Associate Editors and Incoming Editor. Editors shall serve as ex-officio, non-voting members of the Executive Committee. In the year in which there is both an Incoming and Outgoing Editor, the Outgoing Editor serves as the ex-officio, non-voting member of the Executive Committee.

4.  The Society shall publish a book series with the goal of disseminating results of research and scholarly writing in the area of psychology and law. The editor of the book series shall be nominated by the Nominations and Awards Committee, in consultation with the Publications and Communications Committee, such appointment subject to the approval of the Executive Committee. The Editor shall be appointed for a five-year term and shall serve as a non-voting, ex-officio member of the Executive Committee. By mutual consent of the book series Editor and the Executive Committee, the appointment may be extended for an additional five-year term, for a maximum of ten years.

### Article VI: Amendments

1.  Amendments to these By-Laws may be proposed by a majority vote of the Executive Committee or by a majority vote of the membership present at any annual meeting. Ratification of the proposed amendment requires a two-thirds majority of those of the membership voting, or by a two-thirds vote of those members attending any annual meeting. In either case, notice of the vote on the proposed By-Law Amendment must be published and made widely available to the membership prior to when the vote on the proposed By-Law Amendment occurs.
