---
title: "About"
subtitle: Welcome to the American Psychology-Law Society (AP-LS)
---

## Welcome to the American Psychology-Law Society (AP-LS)

### We are Division 41 of the American Psychological Association. 

AP-LS members and the organization itself work to advance the contributions of psychology to the understanding of law and legal institutions through basic and applied research; promote the education of psychologists in matters of law and the education of legal personnel in matters of psychology, including the appropriate use of psychologists in the legal system; and inform the psychological and legal communities and the general public of current research, educational and service activities in the field of psychology and law.

We enhance well-being, justice, and human rights through the science and practice of psychology in legal contexts.

## Our Mission

The American Psychology-Law Society outlines three goals that reflect the many activities, specialties, and contributions made by our members:

- Advancing the contributions of psychology to the understanding of law and legal institutions through basic and applied research.

- Promoting the education of psychologists in matters of law and the education of legal personnel in matters of psychology.

- Informing the psychological and legal communities and the general public of current research, educational and service activities in the field of psychology and law.

## Vision Statement

The American Psychology-Law Society aspires to excel as a valuable, effective and influential organization advancing the science of psychology-law and the translation of psychology-law knowledge into practice and policy, serving as:

**A uniting force** for psychology-law science and practice.

**The major catalyst** for the stimulation, growth and dissemination of psychology-law science and practice.

**The primary resource** for all psychology-law scholars and practitioners and for members of other disciplines with interests in psychology-law science and practice.

**The premier innovator** in the education, development, and training of psychology-law scientists, practitioners and educators.

**The leading advocate** for psychology-law knowledge and practice informing practitioners, policy makers and the public to use psychology-law knowledge in the pursuit of justice for all citizens.

**A principal leader** and global partner promoting psychology-law knowledge and methods to improve justice in diverse, multicultural and international contexts.

**An effective champion** of the application of psychology-law to promote human rights, dignity, and justice.

## Core Values

The American Psychology-Law Society commits to its vision through a mission based upon the following values:

-   Continual pursuit of excellence

-   Knowledge and application based on methods of science

-   Outstanding service to its members and to society

-   Social justice, diversity, and inclusion

-   Ethical action in all that we do