---
pagetitle: "Leadership"
toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../_site/apls_functions.R")
```

# Leadership

## Officers of the Executive Committee

```{r}
#| echo: false
#| message: false
#| warning: false

content = rowwise_table(
  ~name, ~image, ~url, ~text,
  "Barry Rosenfeld", "presidents/barry_rosenfeld.jpg", "mailto:rosenfeld@fordham.edu", "President",
  "Daniel Murrie", "presidents/daniel_murrie.jpg", "mailto:murrie@virginia.edu", "President-elect",
  "Lora Levett", "presidents/lora_levett.png", "mailto:llevett@ufl.edu", "Past President"
)
div(class = "officer-grid",
  pmap(content, function(name, image, url, text) {
    div(class = "officer-grid__item",
      div(class = "officer-grid__image-container",
        img(class = "officer-grid__image", src = image)
      ),
      div(class = "officer-grid__text",
        h3(class = "officer-grid__name",
          a(class = "officer-grid__link", href = url, name)
        ),
        text
      )
    )
  })
)
```


::: vspace
:::

::: {.column-screen .dark-section}
```{r}
#| label: President info-bar
#| output: asis
#| echo: false
#| warning: false
#| message: false

info <- tibble(
  title = "Looking for information about the past?",
  text = "View our list of past presidents and presidential addresses.",
  ctr = "Learn more",
  link = "presidents/presidents.html",
  icon = "fas fa-scale-balanced"
)

html <- generate_info_bar(info)

cat(html)

```
:::

::: vspace2
:::

```{r}
#| echo: false
content = rowwise_table(
  ~name, ~icon, ~url, ~text,
  "Michael Lamb", "", "mailto:mel37@cam.ac.uk", "Secretary",
  "Jennifer Perillo", "", "mailto:treasurer@ap-ls.org", "Treasurer",
  "Virginia Barber-Rioja", "", "mailto:vibarber@hotmail.com", "Member-at-large",
  "Natalie Anumba", "", "mailto:natalie.anumba@umassmed.edu", "Member-at-large",
  "Christopher Bishop", "", "mailto:bishopC@trinitydc.edu", "Member-at-large",
  "Jason Cantone", "", "mailto:cantone@gmail.com", "APA Council Representative",
  "Margaret Kovera", "", "mailto:mkovera@jjay.cuny.edu", "APA Council Representative",
  "Bradley McAuliff", "", "mailto:bradley.mcauliff@csun.edu", "Law & Human Behavior editor",
  "Meg Ternes", "", "mailto:meg.ternes@smu.ca", "Newsletter editor",
  "Monica Miller", "", "mailto:mkmiller@unr.edu", "Book Series editor",
  "Lindsey Wylie", "", "mailto:webmaster@ap-ls.org", "Website editor",
  "Kamar Tazi", "", "mailto:students@ap-ls.org", "Student Committee Chair"
)
div(class = "grid grid-three",
  pmap(content, function(name, icon, url, text, objective) {
      div(class = "grid__item",
        h3(class = "grid__title",
          tags$i(class = sprintf("bi-%s grid__title-icon", icon)),
          span(class = "grid__title-name", name)
        ),
        p(class = "grid__text", text),
        a(href = url, span(class = "grid__link-box"))
      )
  })
)
```

## 2023 Conference Co-Chairs

```{r}
#| echo: false
content = rowwise_table(
  ~name, ~icon, ~url, ~text,
  "Miko M. Wilford", "", "mailto:conference@ap-ls.org", "2023 AP-LS Conference",
  "Andrea Avila", "", "mailto:conference@ap-ls.org", "2023 AP-LS Conference",
  "Alicia Nijdam-Jones", "", "mailto:alicia.nijdam-jones@umanitoba.ca", "2023 APA Conference ",
  "Andre Kehn", "", "mailto:Andre.kehn@und.edu", "2023 APA Conference"
)
div(class = "officer-grid grid-two",
  pmap(content, function(name, icon, url, text, objective) {
      div(class = "grid__item",
        h3(class = "grid__title",
          tags$i(class = sprintf("bi-%s grid__title-icon", icon)),
          span(class = "grid__title-name", name)
        ),
        p(class = "grid__text", text),
        a(href = url, span(class = "grid__link-box"))
      )
  })
)
```
