---
title: Policy Statements
---

## Statement on Racism, Prejudice and Hate

The mission of the American Psychology-Law Society is to enhance well-being, justice, and human rights through the science and practice of psychology in legal contexts. We stand strongly against racism, prejudice, and hate in all its forms. The tragic deaths of George Floyd, Breonna Taylor, Ahmaud Arbery, Tony McDade, and countless other Black, Indigenous, and People of Color are unacceptable. These instances of horrific violence once again illustrate the profound systemic inequities and injustices toward marginalized and oppressed communities in the United States and around the world broadly and more specifically in our criminal justice, civil justice, legal, and carceral systems.

We recognize that racism does not occur in isolation, and its effects are heightened for people who also experience discrimination based on gender, ethnicity, sexual orientation, gender identity, social class, religion, immigration status, and other identities. Likewise, the negative effects of racism multiply across contexts. Recently, racial/ethnic disparities related to COVID-19, health care access, and the spread of COVID-19 in criminal and juvenile justice systems have magnified these profound inequities and injustices.

We believe that, through research, education, and training, better policies and practices can be developed to make the criminal justice, civil justice, legal, and carceral systems more equitable, just, and responsive to the needs of the communities in which they work.

As AP-LS members, we must engage in dialogue and action to create change within our society, our educational and legal institutions, and in our communities. We must engage in stronger efforts that support equity, inclusion, and just outcomes through our research, practice, teaching, and other professional activities. As a society, we seek to join other organizations to promote justice, put a spotlight on injustice, and condemn racism in all its forms. We stand together with Black, Indigenous, and Communities of Color and other oppressed groups and recommit to working together to ensure justice for all.

## Statement in Response to the Atlanta-area March 2021 Deaths

> *Soon after the tragedy involving the death of George Floyd, AP-LS issued a statement in solidarity and to entrench our strong stand against hate in all forms. In response to the senseless killings of eight individuals in the Atlanta, Georgia area, largely because of the intersectionality of their gender and Asian heritage, AP-LS issues a second statement. AP-LS is committed to finding ways to combat prejudice and discrimination through the research, teaching, and practice of psychological science and law. For further resources and to see the statement issued by the Asian American Psychological Association* {{\<

The mission of the American Psychology-Law Society is to enhance well-being, justice, and human rights through the science and practice of psychology in legal contexts. We stand strongly against misogyny, racism, prejudice, and hate in all forms. On March 16, 2021, eight individuals, including six women of Asian heritage, were senselessly gunned down in the larger Atlanta, Georgia area. Their names are:  Soon Chung Park, Hyun Jung Grant, Suncha Kim, Yong Ae Yue, Delaina Ashley Yaun, Paul Andre Michels, Xiaojie Tan, and Daoyou Feng. These tragic deaths and countless others because of skin color, gender, and background---and their intersection---are unacceptable. Instances of violence and hate against Asian and Asian American/Pacific Islanders (AAPI) in particular have been on the rise; according to the Center for the Study of Hate and Extremism, Anti-Asian hate crime rose 149% in 2020, despite a 7% decrease in hate crime overall. 

March 8, 2021, a mere eight days before the Atlanta-area killings, we celebrated International Women\'s Day. The theme of this year\'s International Women\'s Day was \"Choose to Challenge.\" That is, the theme was to make the choice to challenge and call out bias and inequality against women when we see it---and to raise your right hand in support and commitment.

As a society, AP-LS chooses to raise our right hand for the individuals killed on March 16, 2021, especially those targeted because of their intersectional identity as Asian women. We raise our right hand against all forms of bias, discrimination, prejudice, and inequality. We recognize that prejudice does not occur in isolation, and its effects are heightened for people who experience discrimination based on gender, race, ethnicity, sexual orientation, gender identity, social class, religion, immigration status, and other identities---and the intersection of these. As AP-LS members, we must engage in dialogue and action to create change within our society, our educational and legal institutions, and in our communities. We must speak out against hate, violence, and inequality whenever and wherever it occurs. We must continue to engage in stronger efforts that support equity, inclusion, and just outcomes through our research, practice, teaching, and other professional activities. We are committed to working together to ensure justice for all.

\
