---
title: Graduate Programs in Psychology and Law
title-block-banner: "../../images/default-banner.svg"
categories:
  - Training
---

If you are interested in learning more about graduate programs, please review the links to the degree programs provided on this web site, and also review the Guide to Graduate Programs in Legal and Forensic Psychology, developed by members of the AP-LS Teaching, Training, and Careers Committee (TTC).

<center>
{{< downloadthis files/guide_to_graduate_programs_in_forensic_and_legal_psychology_2020.pdf dname:"graduate-school-guidelines" label="Graduate Programs Guide" icon=download type=primary >}}
</center>

This guide lists current graduate programs in forensic and legal psychology.

Programs are listed alphabetically by degree type: doctoral programs (PhD and PsyD), joint programs (PhD/JD, PsyD/JD, JD/MA, PhD/MLS), and masters-level programs. Each program is described using the same categories (program facts, admission criteria, opportunities for research or practical and funding availability) to help prospective students make informed choices about graduate training and education in psychology and law.

::: callout-note
Additional resources can be found on the [Student Committee website](https://www.apls-students.org/education--training.html)
:::
