---
pagetitle: "2023 American Psychology-Law Society Conference" 
section-divs: false
toc: false
css: index.css
editor: source
description: | 
  The annual conference for the American Psychology-Law Society for 2023 will be held in Philadelphia from March 16-18.
includesource: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("_site/apls_functions.R")
```


```{=html}
    <body id="page-top" data-spy="scroll" data-target="side-menu">
      <nav class="side-menu">
        <ul>
          <li class="hidden active">
            <a class="page-scroll" href="#page-top"></a>
          </li>
          <li>
            <a href="#hotel" class="page-scroll">
              <span class="menu-title">Home</span>
              <span class="dot"></span>
            </a>
          </li>
          <li>
            <a href="#register" class="page-scroll">
              <span class="menu-title">Register</span>
              <span class="dot"></span>
            </a>
          </li>
          <li>
            <a href="#hotel" class="page-scroll">
              <span class="menu-title">Hotel</span>
              <span class="dot"></span>
            </a>
          </li>
          <li>
            <a href="#program" class="page-scroll">
              <span class="menu-title">Schedule</span>
              <span class="dot"></span>
            </a>
          </li>
        </ul>
      </nav>
```


::: column-screen
::: {#home .row .hero-header}
::: col-md-12
[Register now](#register){#btn-guide .btn-action .btn-action .btn .btn-success role="button"} [Conference Program](#program){.btn-action .btn .btn-secondary role="button"}
:::
:::
:::

::: column-screen
```{r}
#| label: TOC
#| echo: false
#| warning: false
#| message: false

content = rowwise_table(~name, ~icon, ~link,
  "Hotel", "building", "hotel.qmd",
    "Registration", "person-badge", "#register",     
    "Program", "journal-text", "#program",
  "Pre-conference", "person-workspace", "#workshops"
)
div(class = "bg-light",
 div(class = "bg-breakout",
    div(class = "inner-container",
      div(class = "boxed-wrapper",
            div(class = "boxed-feature-grid",
          pmap(content, function(name, icon, link) {
            div(class = "boxed-feature-grid__item",
              div(class = "boxed-feature-grid__icon",
                a(href = link, class = "boxed-feature-grid__link",
                  tags$i(class = sprintf("bi-%s boxed-feature-grid__i", icon))
                )),
    div(class = "boxed-feature-grid__title", name)
)
          })
        )
      )
    )
  )
)

```
:::

:::

::: {.date}
<p>
25
<span>May</span>
</p>
:::



<i class="bi bi-easel-fill"></i>



## Register to Attend {#register}

Registration is now open! Early Bird registration rates available on or before January 31, 2023. Additional pricing information listed below.

[{{< fa user-plus >}} Register Now](https://apls.memberclicks.net/2023_conf_registration){.btn-action .btn .btn-primary role="button"}

```{=html}

<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #FBF9F4;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #FBF9F4;
}
</style>
</head>
<body>

<h3>Registration Rates</h3>

<table>
  <tr>
    <th>Status</th>
    <th>Early Bird <br>(before Jan 31)</th>
    <th>Regular <br>(on Feb 1)</th>
  </tr>
  <tr>
    <td>Full Member</td>
    <td>$245</td>
    <td>$275</td>
  </tr>
  <tr>
    <td>Early Career Professional <br> Member</td>
    <td>$180</td>
    <td>$210</td>
  </tr>
  <tr>
    <td>Student Member</td>
    <td>$65</td>
    <td>$95</td>
  </tr>
  <tr>
    <td>Student Member <em>First-Author Presenter</em></td>
    <td>$25</td>
    <td>$25</td>
  </tr>
  <tr>
    <td>Student Non-member</td>
    <td>$115</td>
    <td>$145</td>
  </tr>
  <tr>
    <td>Non-member</td>
    <td>$330</td>
    <td>$400</td>
  </tr>
</table>

</body>
</html>
```
:::

```{r}
#| label: info-bar
#| output: asis
#| echo: false
#| warning: false
#| message: false

info <- tibble(
  title = "Need help with registration costs?",
  text = "Become a Student Volunteer.",
  ctr = "Contact office",
  link = "mailto:office@ap-ls.org",
  icon = "fas fa-hand-holding-dollar"
)

students <- generate_info_bar(info)

cat(students)

```

::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

## Pre-conference Workshops

### Wednesday March 15, 2023
