---
title: Assessment
---
### 10.01 Focus on Legally Relevant Factors
Forensic examiners seek to assist the trier of fact to understand evidence or determine a fact in issue, and they provide information that is most relevant to the psycholegal issue.  In reports and testimony forensic practitioners typically provide information about examinees’ functional abilities, capacities, knowledge, and beliefs, and address their opinions and recommendations to the identified psycholegal issues (American Bar Association and American Psychological Assocation, 2008; Grisso, 1986, 2003; Heilbrun, Marczyk, DeMatteo, & Mack-Allen, 2007).

Forensic practitioners are encouraged to consider the problems that may arise by using a clinical diagnosis in some forensic contexts, and consider and qualify their opinions and testimony appropriately.

### 10.02 Selection and Use of Assessment Procedures
Forensic practitioners use assessment procedures in the manner and for the purposes that are appropriate in light of the research on or evidence of their usefulness and proper application (EPPCC Standard 9.02, American Educational Research Association, American Psychological Association, & National Council on Measurement in Education, in press9).  This includes assessment techniques, interviews, tests, instruments, and other procedures and their administration, adaptation, scoring, and interpretation, including computerized scoring and interpretation systems.

Forensic practitioners use assessment instruments whose validity and reliability have been established for use with members of the population assessed.  When such validity and reliability have not been established, forensic practitioners consider and describe the strengths and limitations of their findings.  Forensic practitioners use assessment methods that are appropriate to an examinee's language preference and competence, unless the use of an alternative language is relevant to the assessment issues (EPPCC Standard 9.02).

Assessment in forensic contexts differs from assessment in therapeutic contexts in important ways that forensic practitioners strive to take into account when conducting forensic examinations.  Forensic practitioners seek to consider the strengths and limitations of employing traditional assessment procedures in forensic examinations (American Educational Research Association, American Psychological Association, & National Council on Measurement in Education, in press).    Given the stakes involved in forensic contexts, forensic practitioners strive to ensure the integrity and security of test materials and results (American Educational Research Association, American Psychological Association, & National Council on Measurement in Education, in press9).   

When the validity of an assessment technique has not been established in the forensic context or setting in which it is being used, the forensic practitioner seeks to describe the strengths and limitations of any test results and explain the extrapolation of these data to the forensic context Because of the many differences between forensic and therapeutic contexts, forensic practitioners consider and seek to make known that some examination results may warrant substantially different interpretation when administered in forensic contexts (American Educational Research Association, American Psychological Association, & National Council on Measurement in Education, in press). 

Forensic practitioners consider and seek to make known that forensic examination results can be affected by factors unique to, or differentially present in, forensic contexts including response style, voluntariness of participation, and situational stress associated with involvement in forensic or legal matters (American Educational Research Association, American Psychological Association, & National Council on Measurement in Education, in press).

### 10.03 Appreciation of Individual Differences
When interpreting assessment results forensic practitioners consider the purpose of the assessment as well as the various test factors, test-taking abilities, and other characteristics of the person being assessed, such as situational, personal, linguistic, and cultural differences that might affect their judgments or reduce the accuracy of their interpretations (EPPCC Standard 9.06).  Forensic practitioners strive to identify any significant strengths and limitations of their procedures and interpretations.

Forensic practitioners are encouraged to consider how the assessment process may be impacted by any disability an examinee is experiencing, make  accommodations as possible, and consider such when interpreting and communicating the results of the assessment (American Psychological Association Task Force on Guidelines for Assessment and treatment of Persons with Disabilities, 2011).

### 10.04 Consideration of Assessment Settings
In order to maximize the validity of assessment results, forensic practitioners strive to conduct evaluations in settings that provide adequate comfort, safety and privacy.       

### 10.05 Provision of Assessment Feedback
Forensic practitioners take reasonable steps to explain assessment results to the examinee or a designated representative in language they can understand (EPPCC Standard 9.10).  In those circumstances in which communication about assessment results is precluded, the forensic practitioner explains this to the examinee in advance (EPPCC Standard 9.10).

Forensic practitioners seek to provide information about professional work in a manner consistent with professional and legal standards for the disclosure of test data or results, interpretation of data, and the factual bases for conclusions.

### 10.06 Documentation and Compilation of Data Considered
Forensic practitioners are encouraged to recognize the importance of documenting all data they consider with enough detail and quality to allow for reasonable judicial scrutiny and adequate discovery by all parties. This documentation includes, but is not limited to, letters and consultations; notes, recordings, and transcriptions; assessment and test data, scoring reports and interpretations; and all other records in any form or medium that were created or exchanged in connection with a matter. 

When contemplating third party observation or audio/video-recording of examinations forensic practitioners strive to consider any law that may control such matters, the need for transparency and documentation, and the potential impact of observation or recording on the validity of the examination and test security (American Psychological Association Committee on Psychological Tests and Assessment, 2007). 

### 10.07 Provision of Documentation
Pursuant to proper subpoenas or court orders, or other legally proper consent from authorized persons, forensic practitioners seek to make available all documentation described in 10.05, all financial records related to the matter, and any other records including reports (and draft reports if they have been provided to a party, attorney, or other entity for review), that might reasonably be related to the opinions to be expressed. 

### 10.08 Recordkeeping
Forensic practitioners establish and maintain a system of recordkeeping and professional communication (EPPCC Standard 6.01; American Psychological Association, 2007), and attend to relevant laws and rules.  When indicated by the extent of the rights, liberties, and properties that may be at risk, the complexity of the case, the amount and legal significance of unique evidence in the care and control of the forensic practitioner, and the likelihood of future appeal, forensic practitioners strive to inform the retaining party of the limits of recordkeeping times. If requested to do so, forensic practitioners consider maintaining such records until notified that all appeals in the matter have been exhausted, or  sending a copy of any unique components/aspects of the record in their care and control to the retaining party before destruction of the record.