---
title: Professional and other public communications
---
### 11.01 Accuracy, Fairness, and Avoidance of Deception
Forensic practitioners make reasonable efforts to ensure that the products of their services, as well as their own public statements and professional reports and testimony, are communicated in ways that promote understanding and avoid deception (EPPCC Standard 5.01).

When in their role as expert to the court or other tribunals, the role of forensic practitioners is to facilitate understanding of the evidence or dispute.

Consistent with legal and ethical requirements, forensic practitioners do not distort or withhold relevant evidence or opinion in reports or testimony.  When responding to discovery requests and providing sworn testimony, forensic practitioners strive to have readily available for inspection all data which they considered, regardless of whether the data supports their opinion, subject to and consistent with court order, relevant rules of evidence, test security issues, and professional standards (American Educational Research Association, American Psychological Association, & National Council on Measurement in Education, in press; American Psychological Association Committee on Legal Issues, 2006; Bank & Packer, 2007; Golding, 1990).

When providing reports and other sworn statements or testimony in any form, forensic practitioners strive to present their conclusions, evidence, opinions, or other professional products in a fair manner.  Forensic practitioners do not, by either commission or omission, participate in misrepresentation of their evidence, nor do they participate in partisan attempts to avoid, deny or subvert the presentation of evidence contrary to their own position or opinion (EPPCC Standard 5.01).  This does not preclude forensic practitioners from forcefully presenting the data and reasoning upon which a conclusion or professional product is based.

### 11.02 Differentiating Observations, Inferences, and Conclusions
In their communications, forensic practitioners strive to distinguish observations, inferences, and conclusions.  Forensic practitioners are encouraged to explain the relationship between their expert opinions and the legal issues and facts of the case at hand.

### 11.03 Disclosing Sources of Information and Bases of Opinions
Forensic practitioners are encouraged to disclose all sources of information obtained in the course of their professional services, and to identify the source of each piece of information that was considered and relied upon in formulating a particular conclusion, opinion or other professional product.

### 11.04 Comprehensive and Accurate Presentation of Opinions in Reports and Testimony
Consistent with relevant law and rules of evidence, when providing professional reports and other sworn statements or testimony, forensic practitioners strive to offer a complete statement of all relevant opinions that they formed within the scope of their work on the case, the basis and reasoning underlying the opinions, the salient data or other information that was considered in forming the opinions, and an indication of any additional evidence that may be used in support of the opinions to be offered.  The specific substance of forensic reports is determined by the type of psycholegal issue at hand as well as relevant laws or rules in the jurisdiction in which the work is completed.

Forensic practitioners are encouraged to limit discussion of background information that does not bear directly upon the legal purpose of the examination or consultation.  Forensic practitioners avoid offering information that is irrelevant and that does not provide a substantial basis of support for their opinions, except when required by law (EPPCC Standard 4.04).

### 11.05 Commenting Upon Other Professionals and Participants in Legal Proceedings
When evaluating or commenting upon the work or qualifications of other professionals involved in legal proceedings, forensic practitioners seek to represent their disagreements in a professional and respectful tone, and base them on a fair examination of the data, theories, standards and opinions of the other expert or party. 

When describing or commenting upon clients, examinees, or other participants in legal proceedings, forensic practitioners strive to do so in a fair and impartial manner.  Forensic practitioners strive to report the representations, opinions, and statements of clients, examinees, or other participants in a fair and impartial manner. 

### 11.06 Out of Court Statements
Ordinarily, forensic practitioners seek to avoid making detailed public (out-of-court) statements about legal proceedings in which they have been involved.  However, sometimes public statements may serve important goals such as educating the public about the role of forensic practitioners in the legal system, the appropriate practice of forensic psychology, and psychological and legal issues that are relevant to the matter at hand.    When making public statements, forensic practitioners refrain from releasing private, confidential, or privileged information, and attempt to protect persons from harm, misuse, or misrepresentation as a result of their statements (EPPCC Standard 4.05).

### 11.07 Commenting Upon Legal Proceedings   
Forensic practitioners strive to address particular legal proceedings in publications or communications only to the extent that the information relied upon is part of a public record, or when consent for that use has been properly obtained from any party holding any relevant privilege (also see Section 8.04). 

When offering public statements about specific cases in which they have not been involved, forensic practitioners offer opinions for which there is sufficient information or data and make clear the limitations of their statements and opinions resulting from having had no direct knowledge of or involvement with the case (EPPCC Standard 9.01).