---
title: Competence
---

### 2.01 Scope of Competence 
When determining one's competence to provide services in a particular matter, forensic practitioners may consider a variety of factors including the relative complexity and specialized nature of the service, relevant training and experience, the preparation and study they are able to devote to the matter, and the opportunity for consultation with a professional of established competence in the subject matter in question. Even with regard to subjects in which they are expert, forensic practitioners may choose to consult with colleagues.

### 2.02 Gaining and Maintaining Competence
Competence can be acquired through various combinations of education, training, supervised experience, consultation, study, and professional experience. Forensic practitioners planning to provide services, teach, or conduct research involving populations, areas, techniques, or technologies that are new to them are encouraged to undertake relevant education, training, supervised experience, consultation, or study.

Forensic practitioners make ongoing efforts to develop and maintain their competencies (EPPCC Section 2.03). To maintain the requisite knowledge and skill, forensic practitioners keep abreast of developments in the fields of psychology and the law.

### 2.03 Representing Competencies Consistent with the EPPCC
Forensic practitioners adequately and accurately inform all recipients of their services (e.g., attorneys, tribunals) about relevant aspects of the nature and extent of their experience, training, credentials, and qualifications, and how they were obtained (EPPCC Standard 5.01)

### 2.04 Knowledge of the Legal System 
Forensic practitioners recognize the importance of obtaining a fundamental and reasonable level of knowledge and understanding of the legal and professional standards, laws, rules, and precedents that govern their participation in legal proceedings and that guide the impact of their services on service recipients (EPPCC Standard 2.01).

Forensic practitioners aspire to manage their professional conduct in a manner that does not threaten or impair the rights of affected individuals. They may consult with, and refer others to, legal counsel on matters of law. Although they do not provide formal legal advice or opinions, forensic practitioners may provide information about the legal process to others based on their knowledge and experience. They strive to distinguish this from legal opinions, however, and encourage consultation with attorneys as appropriate.

### 2.05 Knowledge of the Scientific Foundation for Opinions and Testimony
Forensic practitioners seek to provide opinions and testimony that are sufficiently based upon adequate scientific foundation, and reliable and valid principles and methods that have been applied appropriately to the facts of the case.

When providing opinions and testimony that are based on novel or emerging principles and

methods, forensic practitioners seek to make known the status and limitations of these principles and methods.

### 2.06 Knowledge of the Scientific Foundation for Teaching and Research 
Forensic practitioners engage in teaching and research activities in which they have adequate knowledge, experience, and education (EPPCC Standard 2.01), and they acknowledge relevant limitations and caveats inherent in procedures and conclusions (EPPCC Standard 5.01).

### 2.07 Considering the Impact of Personal Beliefs and Experience 
Forensic practitioners recognize that their own cultures, attitudes, values, beliefs, opinions, or biases may affect their ability to practice in a competent and impartial manner. When such factors may diminish their ability to practice in a competent and impartial manner, forensic practitioners may take steps to correct or limit such effects, decline participation in the matter, or limit their participation in a manner that is consistent with professional obligations.

### 2.08 Appreciation of Individual and Group Differences 
When scientific or professional knowledge in the discipline of psychology establishes that an understanding of factors associated with age, gender, gender identity, race, ethnicity, culture, national origin, religion, sexual orientation, disability, language, socioeconomic status, or other relevant individual and cultural differences affects implementation or use of their services or research, forensic practitioners consider the boundaries of their expertise, make an appropriate referral if indicated, or gain the necessary training, experience, consultation, or supervision (EPPCC Standard 2.01, American Psychological Association, 2003; American Psychological Association, 2004; American Psychological Association, 2011c; American Psychological Association, in press; American Psychological Association Task Force on Guidelines for Assessment and Treatment of Persons with Disabilities, 2011).

Forensic practitioners strive to understand how factors associated with age, gender, gender identity, race, ethnicity, culture, national origin, religion, sexual orientation, disability, language, socioeconomic status, or other relevant individual and cultural differences may affect and be related to the basis for people's contact and involvement with the legal system.

Forensic practitioners do not engage in unfair discrimination based on such factors or on any basis proscribed by law (EPPCC Standard 3.01). They strive to take steps to correct or limit the effects of such factors on their work, decline participation in the matter, or limit their participation in a manner that is consistent with professional obligations.

### 2.09 Appropriate Use of Services and Products 
Forensic practitioners are encouraged to make reasonable efforts to guard against misuse of their services and exercise professional discretion in addressing such misuses.
