---
title: Conflicts in practice
---
> In forensic psychology practice conflicting responsibilities and demands may be encountered.  When conflicts occur, forensic practitioners seek to make the conflict known to the relevant parties or agencies, and consider the rights and interests of the relevant parties or agencies in their attempts to resolve the conflict.    

### 7.01 Conflicts with Legal Authority
When their responsibilities conflict with law, regulations, or other governing legal authority, forensic practitioners make known their commitment to the EPPCC, and take steps to resolve the conflict.  In situations in which the EPPCC or Guidelines are in conflict with the  law, attempts to resolve the conflict are made in accordance with the EPPCC (EPPCC Standard 1.02).  

When the conflict cannot be resolved by such means, forensic practitioners may adhere to the requirements of the law, regulations, or other governing legal authority, but only to the extent required and not in any way that violates a person’s human rights (EPPCC Standard 1.03).

Forensic practitioners are encouraged to consider the appropriateness of complying with court orders when such compliance creates potential conflicts with professional standards of practice.

### 7.02 Conflicts with Organizational Demands
When the demands of an organization with which they are affiliated or for whom they are working conflict with their professional responsibilities and obligations, forensic practitioners strive to clarify the nature of the conflict and, to the extent feasible, resolve the conflict in a way consistent with professional obligations and responsibilities (EPPCC Standard 1.03).

### 7.03 Resolving Ethical Issues with Fellow Professionals
When an apparent or potential ethical violation has caused, or is likely to cause, substantial harm, forensic practitioners are encouraged to take action appropriate to the situation and consider a number of factors including the nature and the immediacy of the potential harm; applicable privacy, confidentiality, and privilege; how the rights of the relevant parties may be affected by a particular course of action; and any other legal or ethical obligations (EPPCC Standard 1.04). Steps to resolve perceived ethical conflicts may include, but are not be limited to, obtaining the consultation of knowledgeable colleagues, obtaining the advice of independent counsel, and conferring directly with the client.

When forensic practitioners believe there may have been an ethical violation by another professional, an attempt is made to resolve the issue by bringing it to the attention of that individual, if that attempt does not violate any rights or privileges that may be involved, and if an informal resolution appears appropriate (EPPCC Standard 1.04).  If this does not result in a satisfactory resolution, the forensic practitioner may have to take further action appropriate to the situation, including making a report to third parties of the perceived ethical violation (EPPCC Standard 1.05).   In most instances, in order to minimize unforeseen risks to the party’s rights in the legal matter, forensic practitioners consider consulting with the client before attempting to resolve a perceived ethical violation with another professional.