---
title: Diligence
---

### 3.01 Provision of Services 
Forensic practitioners are encouraged to seek explicit agreements that define the scope of, time-frame of, and compensation for their services. In the event that a client breaches the contract or acts in a way that would require the practitioner to violate ethical, legal or professional obligations, the forensic practitioner may terminate the relationship.

Forensic practitioners strive to act with reasonable diligence and promptness in providing agreed-upon and reasonably anticipated services. Forensic practitioners are not bound, however, to provide services not reasonably anticipated when retained, nor to provide every possible aspect or variation of service. Instead, forensic practitioners may exercise professional discretion in determining the extent and means by which services are provided and agreements are fulfilled.

### 3.02 Responsiveness 
Forensic practitioners seek to manage their workloads so that services can be provided thoroughly, competently, and promptly. They recognize that acting with reasonable promptness, however, does not require the forensic practitioner to acquiesce to service demands not reasonably anticipated at the time the service was requested, nor does it require the forensic practitioner to provide services if the client has not acted in a manner consistent with existing agreements, including payment of fees.

### 3.03 Communication
Forensic practitioners strive to keep their clients reasonably informed about the status of their services, comply with their clients' reasonable requests for information, and consult with their clients about any substantial limitation on their conduct or performance that may arise when they reasonably believe that their clients expect a service that is not consistent with their professional obligations. Forensic practitioners attempt to keep their clients reasonably informed regarding new facts, opinions, or other potential evidence that may be relevant and applicable.

### 3.04 Termination of Services
The forensic practitioner seeks to carry through to conclusion all matters undertaken for a client unless the forensic practitioner-client relationship is terminated. When a forensic practitioner's employment is limited to a specific matter, the relationship may terminate when the matter has been resolved, anticipated services have been completed, or the agreement has been violated.
