---
title: Fees
---
### 5.01 Determining Fees
When determining fees forensic practitioners may consider salient factors such as their experience providing the service, the time and labor required, the novelty and difficulty of the questions involved, the skill required to perform the service, the fee customarily charged for similar forensic services, the likelihood that the acceptance of the particular employment will preclude other employment, the time limitations imposed by the client or circumstances, the nature and length of the professional relationship with the client, the client’s ability to pay for the service, and any legal requirements.

### 5.02 Fee Arrangements
Forensic practitioners are encouraged to make clear to the client the likely cost of services whenever it is feasible, and make appropriate provisions in those cases in which the costs of services is greater than anticipated or the client’s ability to pay for services changes in some way.          

Forensic practitioners seek to avoid undue influence that might result from financial compensation or other gains.  Because of the threat to impartiality presented by the acceptance of contingent fees and associated legal prohibitions, forensic practitioners strive to avoid providing professional services on the basis of contingent fees.  Letters of protection, financial guarantees, and other security for payment of fees in the future are not considered contingent fees unless payment is dependent on the outcome of the matter. 

### 5.03 Pro Bono Services
Forensic psychologists recognize that some persons may have limited access to legal services as a function of financial disadvantage and strive to contribute a portion of their professional time for little or no compensation or personal advantage (EPPCC Principle E). 