---
title: Methods and procedures
---
### 9.01 Use of Appropriate Methods
Forensic practitioners strive to utilize appropriate methods and procedures in their work.  When performing examinations, treatment, consultation, educational activities or scholarly investigations, forensic practitioners seek to maintain integrity by examining the issue or problem at hand from all reasonable perspectives and seek information that will differentially test plausible rival hypotheses.

### 9.02 Use of Multiple Sources of Information
Forensic practitioners ordinarily avoid relying solely on one source of data, and corroborate important data whenever feasible (American Educational Research Association, American Psychological Association, & National Council on Measurement in Education, in press).  When relying upon data that have not been corroborated, forensic practitioners seek to make known the uncorroborated status of the data, any associated strengths and limitations, and the reasons for relying upon the data.

### 9.03 Opinions Regarding Persons Not Examined
Forensic practitioners recognize their obligations to only provide written or oral evidence about the psychological characteristics of particular individuals when they have sufficient information or data to form an adequate foundation for those opinions or to substantiate their findings (EPPCC Standard 9.01).  Forensic practitioners seek to make reasonable efforts to obtain such information or data, and they document their efforts to obtain it.  When it is not possible or feasible to examine individuals about whom they are offering an opinion, forensic practitioners strive to make clear the impact of such limitations on the reliability and validity of their professional products, opinions, or testimony.

When conducting a record review or providing consultation or supervision that does not warrant an individual examination, forensic practitioners seek to identify the sources of information on which they are basing their opinions and recommendations, including any substantial limitations to their opinions and recommendations.