---
title: References
---

American Bar Association & American Psychological Association. (2008). Assessment of older adults with diminished capacity: A handbook for psychologists. Washington, DC: American Bar Association and American Psychological Association.

American Educational Research Association, American Psychological Association, & National Council on Measurement in Education (in press). Standards for educational and psychological testing (third edition). Washington, DC: American Educational Research Association.

American Psychological Association (in press). Guidelines for psychological practice with gay, lesbian, and bisexual clients. American Psychologist.

American Psychological Association (2003). Guidelines on multicultural education, training, research, practice, and organizational change for psychologists. American Psychologist, 58, 377-402.

American Psychological Association. (2004). Guidelines for psychological practice with older adults. American Psychologist, 59, 4, 236–260. Washington, DC:  Author.

American Psychological Association (2007). Record keeping guidelines, American Psychologist, 62, 993-1004. American Psychological Association (2010). Ethical principles of psychologists and code of conduct: Retrieved July 26, 2010.

American Psychological Association (2010). Guidelines for child custody evaluations in legal proceedings. American Psychologist, 65, 863-867.

American Psychological Association (2011a). Guidelines for psychological evaluations in child protection matters.  Washington, DC: Author.

American Psychological Association (2011b). Guidelines for the practice of parenting coordination. Washington, DC: Author.

American Psychological Assocation (2011c). Guidelines for the evaluation of dementia and age related cognitive change.  Washington, DC: Author. 

American Psychological Association Committee on Legal Issues (2006). Strategies for private practitioners coping with subpoenas or compelled testimony for client records or test data. Professional Psychology: Research and practice, 37, 215-222.

American Psychological Association Committee on Psychological Tests and Assessment (2007). Statement on third party observers in psychological testing and assessment: A Framework for Decision Making.  Washington, DC: Author.  

American Psychological Association Task Force on Guidelines for Assessment and treatment of Persons with Disabilities (2011). Guidelines for assessment of and intervention with persons with disabilities. Washington, DC: Author.

Bank, S., & Packer, R. (2007). Expert witness testimony: Law, ethics, and practice. In  A.M. Goldstein (Ed.), Forensic Psychology: Emerging topics and expanding roles (pp. 421-445). Hoboken, NJ: J. Wiley & Sons.

Golding, S. L. (1990). Mental health professionals and the courts: The ethics of expertise. International Journal of Law and Psychiatry, 13, 261-307.

Grisso, T. (1986). Evaluating competencies: forensic assessments and instruments, New York: Plenum.

Grisso, T. (2003). Evaluating competencies: forensic assessments and instruments (second edition), New York: Kluwer/Plenum.

Heilbrun, K., Marczyk, G., DeMatteo, D., & Mack-Allen, J. (2007). A Principles-based approach to forensic mental health assessment: Utility and update. In  A.M. Goldstein (Ed.), Forensic Psychology: Emerging topics and expanding roles (pp. 45-72). Hoboken, NJ: J. Wiley & Sons.

Melton, G., Petrila,, J., Poythress, N., & slobogin, 1987). Psychological evaluations for the courts: A handbook for mental health professionals and lawyers. New York: Guilford.

Melton, G., Petrila,, J., Poythress, N., & Slobogin, C. (1997). Psychological evaluations for the courts: A handbook for mental health professionals and lawyers (second edition). New York: Guilford.

Melton, G., Petrila,, J., Poythress, N., & Slobogin, C., Lyons, P., & Otto, R. K.  (2007). Psychological evaluations for the courts: A handbook for mental health professionals and lawyers (third edition). New York: Guilford.  

Monahan, J. (Ed.). (1980). Who is the client? The ethics of psychological intervention in the criminal justice system Washington, D. C.:  American Psychological Association. 

Rogers, R. (Ed.) (1988). Clinical assessment of malingering and deception. New York: Guilford.

Rogers, R. (Ed.)(1997). Clinical assessment of malingering and deception (second edition). New York: Guilford.

Rogers, R. (Ed.)(2008). Clinical assessment of malingering and deception (third edition). New York: Guilford.