---
title: Relationship
---

Whether a forensic practitioner-client relationship exists depends on the circumstances and is determined by a number of factors which may include the information exchanged between the potential client and the forensic practitioner prior to, or at the initiation of, any contact or service, the nature of the interaction, and the purpose of the interaction.

In their work, forensic practitioners recognize that relationships are established with those who retain their services (e.g., retaining parties, employers, insurers, the court) and those with whom they interact (e.g., examinees, collateral contacts, research participants, students).  Forensic practitioners recognize that associated obligations and duties vary as a function of the nature of the relationship. 

4.01 Responsibilities to Retaining Parties
Most responsibilities to the retaining party attach only after the retaining party has requested and the forensic practitioner has agreed to render professional services and an agreement regarding compensation has been reached.  Forensic practitioners are aware that there are some responsibilities, such as privacy, confidentiality, and privilege that may attach when the forensic practitioner agrees to consider whether a forensic practitioner-retaining party relationship shall be established.  Forensic practitioners, prior to entering into a contract, may direct the potential retaining party not to reveal any confidential or privileged information as a way of protecting the retaining party’s interest in case a conflict exists as a result of pre-existing relationships.

At the initiation of any request for service, forensic practitioners seek to clarify the nature of the relationship and the services to be provided including the role of the forensic practitioner (e.g., trial consultant, forensic examiner, treatment provider, expert witness, research consultant); which person or entity is the client; the probable uses of the services provided or information obtained; and any limitations to privacy, confidentiality, or privilege.

4.02 Multiple Relationships
A multiple relationship occurs when a forensic practitioner is in a professional role with a person and, at the same time or at a subsequent time, is in a different role with the same person; is involved in a personal, fiscal, or other relationship with an adverse party; at the same time is in a relationship with a person closely associated with or related to the person with whom the forensic practitioner has the professional relationship; or offers or agrees to enter into another relationship in the future with the person or a person closely associated with or related to the person (EPPCC Standard 3.05).

Forensic practitioners strive to recognize the potential conflicts of interest and threats to objectivity inherent in multiple relationships.  Forensic practitioners are encouraged to recognize that some personal and professional relationships may interfere with their ability to practice in a competent and impartial manner and they seek to minimize any detrimental effects by avoiding involvement in such matters whenever feasible or limiting their assistance in a manner that is consistent with professional obligations.

4.02.01 Therapeutic-Forensic Role Conflicts
Providing forensic and therapeutic psychological services to the same individual or closely related individuals involves multiple relationships that may impair  objectivity and/or cause exploitation or other harm. Therefore, when requested or ordered to provide either concurrent or sequential forensic and therapeutic services, forensic practitioners are encouraged to disclose the potential risk and make reasonable efforts to refer the request to another qualified provider.  If referral is not possible, the forensic practitioner is encouraged to consider the risks and benefits to all parties and to the legal system or entity likely to be impacted, the possibility of separating each service widely in time, seeking judicial review and direction, and consulting with knowledgeable colleagues. When providing both forensic and therapeutic services, forensic practitioners seek to minimize the potential negative effects of this circumstance (EPPCC Standard 3.05).

4.02.02 Expert Testimony by Practitioners Providing Therapeutic Services
Providing expert testimony about a patient who is a participant in a legal matter does not necessarily involve the practice of forensic psychology even when that testimony is relevant to a psycholegal issue before the decision-maker.  For example, providing testimony on matters such as a patient’s reported history or other statements, mental status, diagnosis, progress, prognosis, and treatment would not ordinarily be considered forensic practice even when the testimony is related to a psycholegal issue before the decision-maker.  In contrast, rendering opinions and providing testimony about a person on psycholegal issues (e.g., criminal responsibility, legal causation, proximate cause, trial competence, testamentary capacity, the relative merits of parenting arrangements) would ordinarily be considered the practice of forensic psychology.

Consistent with their ethical obligations to base their opinions on information and techniques sufficient to substantiate their findings (EPPCC Standards 2.04, 9.01), forensic practitioners are encouraged to provide testimony only on those issues for which they have adequate foundation and only when a reasonable forensic practitioner engaged in similar circumstances would determine that the ability to make a proper decision is unlikely to be impaired.  As with testimony regarding forensic examinees, the forensic practitioner strives to identify any substantive limitations that may affect the reliability and validity of the facts or opinions offered, and communicates these to the decision maker.

4.02.03 Provision of Forensic Therapeutic Services
Although some therapeutic services can be considered forensic in nature, the fact that therapeutic services are ordered by the court does not necessarily make them forensic.

In determining whether a therapeutic service should be considered the practice of forensic psychology, psychologists are encouraged to consider the potential impact of the legal context on treatment, the potential for treatment to impact the psycholegal issues involved in the case, and whether another reasonable psychologist in a similar position would consider the service to be forensic and these Guidelines to be applicable.

Therapeutic services can have significant effects on current or future legal proceedings.  Forensic practitioners are encouraged to consider these effects and minimize any unintended or negative effects on such proceedings or therapy when they provide therapeutic services in forensic contexts. 

4.03 Provision of Emergency Mental Health Services to Forensic Examinees
When providing forensic examination services an emergency may arise that requires the practitioner to provide short term therapeutic services to the examinee in order to prevent imminent harm to the examinee or others.  In such cases, the forensic practitioner is encouraged to limit disclosure of information and inform the retaining attorney, legal representative, or the court in an appropriate manner.  Upon providing emergency treatment to examinees, forensic practitioners consider whether they can continue in a forensic role with that individual so that potential for harm to the recipient of services is avoided (EPPCC 3.04). 