---
title: Responsibilities
---

1.01 Integrity Forensic practitioners strive for accuracy, honesty, and truthfulness in the science, teaching, and practice of forensic psychology and they strive to resist partisan pressures to provide services in any ways that might tend to be misleading or inaccurate.

1.02 Impartiality and Fairness When offering expert opinion to be relied upon by a decision maker, providing forensic therapeutic services, or teaching or conducting research, forensic practitioners strive for accuracy, impartiality, fairness, and independence (EPPCC Standard 2.01). Forensic practitioners recognize the adversarial nature of the legal system and strive to treat all participants and weigh all data, opinions, and rival hypotheses impartially.

When conducting forensic examinations, forensic practitioners strive to be unbiased and impartial, and avoid partisan presentation of unrepresentative, incomplete, or inaccurate evidence that might mislead finders of fact. This guideline does not preclude forceful presentation of the data and reasoning upon which a conclusion or professional product is based.

When providing educational services, forensic practitioners seek to represent alternative perspectives, including data, studies, or evidence on both sides of the question, in an accurate, fair and professional manner, and strive to weigh and present all views, facts, or opinions impartially.

When conducting research, forensic practitioners seek to represent results in a fair and impartial manner. Forensic practitioners strive to utilize research designs and scientific methods that adequately and fairly test the questions at hand, and they attempt to resist partisan pressures to develop designs or report results in ways that might be misleading or unfairly bias the results of a test, study, or evaluation.

1.03 Avoiding Conflicts of Interest Forensic practitioners refrain from taking on a professional role when personal, scientific, professional, legal, financial, or other interests or relationships could reasonably be expected to impair their impartiality, competence, or effectiveness, or expose others with whom a professional relationship exists to harm (EPPCC Standard 3.06).

Forensic practitioners are encouraged to identify, make known, and address real or apparent conflicts of interest in an attempt to maintain the public confidence and trust, discharge professional obligations, and maintain responsibility, impartiality, and accountability (EPPCC Standard 3.06). Whenever possible, such conflicts are revealed to all parties as soon as they become known to the psychologist. Forensic practitioners consider whether a prudent and competent forensic practitioner engaged in similar circumstances would determine that the ability to make a proper decision is likely to become impaired under the immediate circumstances.

When a conflict of interest is determined to be manageable, continuing services are provided and documented in a way to manage the conflict, maintain accountability, and preserve the trust of relevant others (also see Section 4.02 below).
