---
title: "membership details"
---

AP-LS is an interdisciplinary organization devoted to scholarship, practice, and public service in psychology and law. The American Psychology-Law Society is both a free-standing organization as well as a division (Division 41) of the American Psychological Association. Members of AP-LS need not be members of APA, although many members belong to both organizations (AP-LS and APA). Membership is open to interested professionals and students in other disciplines beyond psychology. Membership is for the calendar year January 1 - December 31.

Membership in AP-LS entitles one to online access of the journal, Law and Human Behavior and the American Psychology-Law Monthly E-News. AP-LS also sponsors an annual meeting as well as programs at the APA convention. The activities of AP-LS/Division 41 in its brief history have been quite diverse, including developing a collection of course syllabi and teaching materials, conducting a survey of career opportunities in psychology and law, studying special ethical problems in expert testimony, drafting recommendations, and sponsoring an annual conference.

### Membership Information

AP-LS encourages APA members, graduate and undergraduate students, and persons in related fields to consider membership in the Division. Student memberships are encouraged.

<a class="btn btn-primary btn-lg" href="https://apls.memberclicks.net/membership-form#!/" role="button">Become a Member</a>

## Membership Levels

+--------------------------------+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Full Member                    | \$50 per year         | Psychologists who are already Associates or Members of another division of APA may join in that capacity. Those who are Fellows of other divisions may join as members and may be nominated for Fellow status later if they wish. APA elects new division members several times a year and bills new (and old) members in the regular dues statement in the fall. Dues are \$**50.00**.  Non-Psychologists (e.g., lawyers, sociologists) or psychologists who do not belong to APA may join as Members-at-Large by submitting a check for \$50.00. If you join as a Member-at-Large, please send in a vita with your membership application. |
|                                |                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|                                |                       | To obtain Member-at-Large status, you should have either a doctorate in psychology or a related behavioral science or a law degree. If you don't meet this criteria, the Executive Committee of AP-LS will vote at the annual APA Convention to determine whether to waive this requirement if there is evidence satisfactory to the Executive Committee of contribution by an individual to the field of Psychology and Law.                                                                                                                                                                                                                |
+--------------------------------+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### Early Career Professionals | #### \$15.00 Per Year | Those who received a doctoral degree (J.D., Ph.D., Psy.D., M.D., or Ed.D.) within the past 3 years, may join at an introductory rate in one of the membership categories for a reduced fee of \$15.00.  Please make sure you fill out your graduation date (please indicate the 1st of the month if you do not remember the precise date).                                                                                                                                                                                                                                                                                                   |
|                                |                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|                                | \                     | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
+--------------------------------+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### Student Member             | #### \$15.00 Per Year | Undergraduate students, graduate students and law students may join as Associates-at-Large. Undergraduate or graduate students should be enrolled in a social or behavioral science program. Student membership, which also includes a subscription to Law and Human Behavior and the Newsletter, is \$15.00 per year. When filling out the application, please be sure to list the degree(s) you are seeking, the institution you are attending, and your anticipated graduation date (please indicate the 1st of the month if you do not remember the precise date).                                                                       |
|                                |                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| \                              | \                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+--------------------------------+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
