---
title: AP-LS Mid-Career Award
date: last-modified
description: Recognizes members whose work has substantially contributed to the fields of forensic and legal psychology. 
categories: 
  - Distinguished Career
submission-info:  
  sponsor: AP-LS Executive Committee
  deadline: "December 1, `r if (Sys.Date() > lubridate::mdy(paste('December 1', lubridate::year(Sys.Date())))) lubridate::year(Sys.Date()) + 1 else lubridate::year(Sys.Date())`"
links:
- icon: send
  name: Submit here
  url: "murrie@virginia.edu"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../../assets/apls_functions.R")
```

<hr>

::: panel-tabset
## Description

The AP-LS Mid-Career Award recognizes members whose work has already substantially contributed to the fields of forensic and legal psychology.  Up to three awards may be given each year to recognize scholars who have contributed through research, theory, and/or practice within these fields (e.g., experimental, forensic, corrections, etc.). 

## Eligibility

Nominees will have completed their terminal degree 10 - 25 years before the nomination deadline. ***The nominee should be a member of AP-LS.***

## How to Apply

All nominations should be sent in a single pdf document to the  AP-LS Past President by **December 1**. 

::: {.callout-tip appearance="simple"}
## The nomination packet should include: 

-   A copy of the nominee’s CV
-   A letter detailing the nominee’s distinguished contributions to psychology and law; and
-   Any additional letters of support that address the nominee’s service to the field 
:::

:::
