---
title: "Committe Reports"
description: "List of reports and documents prepared by AP-LS Committees"
title-block-banner: "../../images/default-banner.svg"
categories:
  - committees
---

## AP-LS Conference Climate Survey
The American-Law Society (AP-LS) Professional Development of Women (PDW) Committee’s #MeToo panel and follow-up discussion at the 2018 AP-LS conference highlighted concerns related to sexual harassment and other types of discrimination that have been raised by women (and others) about their workplaces and other academic settings (e.g., conferences), which can impact their success in the field. 

The purpose of the Climate Survey was to assess AP-LS members’ and recent AP-LS Conference attendees’ experiences of harassment and exclusion.

{{< downloadthis 2020_Climate_Survey_Results.pdf dname:"climate-survey" label="Download Report" icon=download type=outline-primary >}} 


## Early Career Professionals Survey
The intent of this project and report is to provide new information on ECPs’ perceptions of their education and training opportunities, what ECPs’ needs are, and how AP-LS could best address those needs.

{{< downloadthis Final_ECP_Report.pdf dname:"ecp-survey" label="Download Report" icon=download type=outline-primary >}} 