---
title: Grants-in-Aid for Early Career Professionals
date: last-modified
description: Support (up to $5,000) for early career professionals in conducting research related to psychology and law.
categories: 
  - Early Career Professionals
  - Grants-in-Aid
submission-info:
  sponsor: AP-LS Early Career Professionals Committee
  deadline: October 15
links:
- icon: envelope-at
  name: Contact
  url: "mailto:ecp@apls.org"
- icon: send
  name: Submit here
  url: "https://awards.ap-ls.org/default.asp"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../../assets/apls_functions.R")
```

<hr>

::: panel-tabset
## Description

The AP-LS Committee on Early Career Professionals (ECPs) was formed in 2007 to initiate programs geared toward issues commonly faced by ECPs. ECPs face a number of unique challenges and issues when making the transition from graduate study to professional life. More than ever, today's ECPs are likely to struggle with juggling multiple roles. Challenges faced by ECPs include financial concerns or strains, meeting licensure requirements, developing a professional identify, obtaining tenure, and enhancement of health and wellness, among other issues (Green & Hawley, 2009).

The purpose of this award is to support AP-LS members who are ECPs in conducting research related to psychology and law. It is the committee's desire that these awards are not limited only to members who are psychologists, but instead open to AP-LS members from all backgrounds.

**Award amounts**

Funding up to \$5,000 per award is available. Funding should primarily support research activities and data collection efforts (e.g., equipment, participant payments, software data transcription, hourly payment for research assistants, and expenses incurred at sites away from the home institution while collecting data). Travel to conferences and salary expenses are not eligible costs. Funds for successful proposals will be awarded to the PI's academic institution (via the institution's Office of Sponsored Research or Foundation). No institutional indirect cost recovery will be permitted.

## Eligibility

**To receive an award:**

-   The applicant must be an Early Career Professional, defined by APA as those within **ten years** of receiving their last degree.

-   Applicants and any co-applicants must be classified as ECPs upon the application deadline for that year.

-   Applicants may submit only one award proposal per funding cycle. In addition, to maximize the impact of the program, a strong preference will be given to those applicants who never have received an AP-LS ECP Grants-in-Aid.

-   Under exceptional circumstances, the committee may consider a second award. The possibility of a second award will be a rare occurrence, and the previous award must be completed prior to submitting a second proposal.

-   Proposals that represent "seed money" for larger projects and proposals that are for "standalone" projects will be accepted.

-   Applicants are encouraged but not required to secure matched funding from employers to support the proposed research.

    </p>

    </li>

-   All applicants and any co-applicants must be active members of AP-LS.

::: {callout-note}
These awards are not limited only to AP-LS members who are psychologists; they are open to members from all backgrounds.

But students are not eligible to receive an award.
:::

## How to Apply

Submit a complete proposal to the online portal by October 15 at 11:59 PST.

<a class="btn btn-primary" href="https://awards.ap-ls.org/default.asp" role="button">Click to Apply</a>

## Proposal guidelines

Proposal should include:

1.  PI and co-PI personal information and affiliations;

2.  status of the human subjects review for the project (approval must be obtained prior to disbursement of the award);

3.  explanation regarding attempts to secure matched funding from employer (Contact the ECP committee with any questions);

4.  A 150-word abstract describing the proposed research;

5.  A five-page single-spaced project description with 1-inch margins and 12-pt Times New Roman font or similar. [You can download the formatted template here](https://docs.google.com/document/d/1ZzlGkmBgYTpwdFTZcyCflA8bvdRLFY60/edit?usp=sharing&ouid=108695850738874268529&rtpof=true&sd=true). The description should include:

-   **Statement of the problem:** A clear statement of the research problem and its significance to psychology and law;

-   **Background and aims:** a concise overview of the relevant empirical literature, theoretical background, and/or law related to the research problem;

-   **Method:** a detailed description of the methodology and analytical strategies to be used. Although not required, applicants are encouraged to include an Open Science Practice Statement (or plan) with their application;

-   **Significance:** a brief description of the significance of the project within the field of psychology and law.

6.  A reference list (does not count toward the page limit);

7.  A CV for each PI and co-PI contributing to the project, including a list of "significant collaborators" that includes dissertation and master's thesis advisors, current and past students, co-authors within the last 5 years, editors who have edited a book in which you have a chapter published, and authors who have published in a book you have edited;

8.  A project timeline and a proposed budget that details anticipated expenditures and a budget justification that links the requested funds to the proposed activities (If the applicant has secured additional funding for the proposed research from another funding source, please provide an explanation of how the external funds will be used---additional funding is not required and is not considered among the evaluation criteria);

9.  Suggestions for at least five suggested reviewers for the project with expertise in the content area of the proposal: Suggested reviewers should not include anyone who might have a significant conflict of interest in reviewing the proposal (defined as "significant collaborators" in CV section). Please include the full name and email address of each suggested reviewer.

::: callout-caution
## Keep in mind

All project-related materials (i.e., abstract, description, timeline, budget) should be blinded. Failure to blind materials will disqualify the applicants from the program.
:::

## Proposal Review Criteria

Applications first will be reviewed by at least two external reviewers; proposals will be subject to blind review. After receiving external reviews, the ECP Committee will meet to evaluate the proposals and to make funding decisions. Both the external reviews and a panel summary will be provided to the applicant, regardless of award decision.

In evaluating each proposal, outside reviewers and the panel will evaluate and provide feedback about the intellectual merit and broader impacts of the project using the following criteria:

1.  **Proposal Quality:** What is the quality of the proposed project? Is it methodologically rigorous? Is the method thorough and complete?

2.  **Proposal Contribution:** What is the potential contribution of the proposal to the field of psychology and law? Does it have potential to contribute to advancing knowledge in the field?

3.  **Proposal Originality:** Does the proposal present an original idea in psychology and law? Does the proposal use new or creative methods or viewpoints to address old problems?

4.  **Proposal Broader Impacts:** Does the proposal have potential to benefit society or advance societal outcomes? (see NSF Broader Impact criteria for ideas of broader impacts to address)

5.  **Overall rating:** What is the overall assessment of the proposal? What is the funding recommendation?

## Award Recipients

Awardees must submit yearly progress reports on **Nov. 15** of each year until the project is complete.

Upon completion of the project, awardees must submit an end-of-project report and should consider presenting the results of their research at either a subsequent AP-LS conference or in the division's APA program.

## Mentoring Program

The Early Career Professional’s Committee is introducing a mentoring program for early career researchers who are planning to apply for the Grant in Aid (GiA). 

Through the mentoring program, you can connect with a researcher who was awarded the GiA and ask them questions regarding their experience with the grant, the application process (beyond practical information provided in the general guidance), the role the grant had in their career, or questions related to their proposal.

::: callout-note

Please note that mentors are not reviewers or co-authors and should provide general support in the application process. 

If you’d like to connect with a mentor, please think about three keywords related to your project and send us an email to the [ECP committee](mailto:ecp@ap-ls.org) and include GiA Mentoring program connection request: [your keywords] as the subject. We will do our best to connect you with a mentor.

:::

:::
