---
title: "Law and Human Behavior Call for Papers: Justice, Legitimacy, and Technology"
draft: true
---

Law and Human Behavior is a multidisciplinary forum for manuscripts examining the interface between human behavior and the law, the legal system, and the legal process. Although pure legal analysis falls outside the scope of the journal, Law and Human Behavior publishes compelling conceptual (methodological and theoretical) and empirical papers, and strongly encourages authors to situate their research within the context of the law and discuss implications for criminal justice and/or legal policies and practice. This includes the journal’s requirement that all manuscripts include a public significance statement upfront.


Law and Human Behavior is soliciting submissions for a forthcoming special issue on **Justice, Legitimacy, and Technology**. The power of government institutions depends crucially on the belief that these institutions deserve the public’s respect and deference. One important pillar of institutional legitimacy is the public’s belief that courts, the police, and other governmental bodies follow fair procedures to arrive at fair decisions. Little is known, however, about how recent election disputes; controversial Supreme Court decisions; debates over diversity, equity, and inclusion; and rapid technological advancements affect the public’s belief that government institutions operate in just ways—including with respect to due process, procedural justice, distributive justice, and treating persons with dignity. 

This special issue thus seeks contributions examining the impact of growing social and political polarization on perceptions of whether government institutions operate in procedurally just ways, yield just outcomes, and impart a sense of fairness and respect. Relatedly, we seek works examining how institutions can maintain legitimacy in the face of greater division and inequality. In addition, we welcome contributions examining the role that technology and technological changes play or can play in changing perceptions of government institutions and their operations.

\
We invite work from a variety of fields—including law, psychology, psychiatry, criminal justice, political science, sociology, education, and communication—that explores these questions empirically or that builds on existing empirical work to provide a theoretical account of how polarization or technology does or can affect perceptions of legal processes and resolutions. Examples include how decision-making of legal system actors (e.g., judges, jurors, clinicians) may reflect heuristics, biases, and other processes that demonstrably impact the perceptions formed or held by different stakeholders about the operations of different branches of government (e.g., law enforcement, governance, courts, corrections). Other examples include how greater reliance on artificial intelligence and algorithms to assist or make government decisions buttress or undercut perceptions of due process, procedural justice, distributive justice, and respectfulness of people. Authors can contact the editors of this special issue with any inquires concerning potential submissions, including about fit with the exploratory theme of the special issue, and the desire to feature both theoretical and empirical works.


We request that authors interested in contributing a manuscript for this special issue submit a nonbinding letter of intent by **April 21, 2024**. This letter should include (1) a tentative title; (2) a brief description of the manuscript in 500 words or less; and (3) all authors and affiliations. Please email letters of intent to the special issue’s editors, Brandon Garrett [bgarrett\@law.duke.edu](mailto:bgarrett@law.duke.edu), Christopher King [kingch\@montclair.edu](mailto:kingch@montclair.edu), and David DeMatteo [dsd25\@drexel.edu](mailto:dsd25@drexel.edu).

\

Authors who submit letters of intent will be notified if they are invited to submit a full

manuscript for consideration. The deadline to submit a manuscript for the special issue is **August 11, 2024**. Authors should refer to the [Submission Guidelines](https://www.apa.org/pubs/journals/lhb?tab=1) on the Law and Human Behavior website and prepare their manuscripts in accordance

with the Seventh Edition of the Publication Manual of the American Psychological Association. Note that, for empirical submissions, the journal’s guidelines include important information about open science badges, openness and transparency, and research disclosures. Authors should submit electronically using the [Editorial Manager](https://www.editorialmanager.com/lhb/default.aspx) web portal and specify in their cover letters that they would like their submissions to be considered for the special issue on **Justice, Legitimacy, and Technology**.

\

Questions about the special issue or the potential appropriateness of particular submissions

can be sent to the special issue’s editors: Brandon Garrett [bgarrett\@law.duke.edu](mailto:bgarrett@law.duke.edu), Christopher King [kingch\@montclair.edu](mailto:kingch@montclair.edu), and David DeMatteo [dsd25\@drexel.edu](mailto:dsd25@drexel.edu).
